// Original diagnostic cases. F/C/R are curriculum groupings, not measured prevalence.
// Fields: cause | grouping | reported symptom | collected evidence | repair | verification.
export const ISSUE_GROUPS = {
  'Physical & power': `
Disconnected workstation cable|F|One desk cannot reach any network service.|The workstation reports media disconnected; its patch lead is unseated.|Reconnect the assigned lead at both endpoints.|Confirm link and test the gateway and application.
Administratively disabled access port|F|A connected workstation has no service.|The assigned switch port reports administratively down; its cable is seated.|Enable the authorized access port.|Confirm operational link and application access.
Failed patch lead|F|Connectivity fails at one desk.|The same PC and switch port work with a known-good lead; the original fails wiremap.|Replace and label the defective patch lead.|Retest wiremap and sustained traffic.
Unpowered access switch|F|An entire small office loses wired access.|The switch has no power LEDs and the rack outlet is dead.|Restore the approved power feed and verify the switch boots.|Check all uplinks and representative clients.
Disabled workstation adapter|F|Only one PC is offline.|The operating system shows its Ethernet adapter disabled; switch and cable work for another PC.|Enable the intended adapter.|Confirm link, addressing, and application access.
Wrong wall jack|F|A moved workstation has no link.|The desk uses jack B17 while the active patch-panel circuit is B18.|Move to the documented jack or correct the patching record.|Trace both ends and verify service.
Patch-panel cross-connect error|C|A workstation reaches the wrong network after cabling work.|Tone tracing maps its outlet to a different department port than the print.|Correct the cross-connect against the approved port map.|Verify VLAN, client subnet, and the neighboring circuit.
Copper split pair|C|A cable passes simple continuity but fails under load.|Certification shows split pairs and excessive crosstalk.|Reterminate using the correct pair assignments.|Pass certification and a traffic test.
Excessive copper channel length|C|A distant desk has unstable Ethernet.|The measured channel exceeds the installed cabling design limit and fails certification.|Shorten or redesign the channel using approved infrastructure.|Certify the completed channel.
Damaged RJ45 latch|C|A desk drops offline when its cable is touched.|The plug does not latch; gentle movement opens the link.|Replace the patch cable.|Verify secure seating and stable link.
Incorrect forced link speed|C|A replacement device will not link.|One side is forced to a speed the other does not support.|Align supported speed and negotiation settings.|Confirm negotiated speed and error-free traffic.
Duplex mismatch|C|Transfers are slow despite link-up status.|One end is half duplex and the other full; late collisions increase.|Align negotiation and duplex on both ends.|Confirm matching duplex and no increasing collision counters.
PoE budget exhausted|C|The newest access point does not power on.|The switch log reports denied power and allocated power reaches the available budget.|Provide approved additional PoE capacity or redistribute loads.|Verify every required powered device remains online.
Insufficient PoE class|C|A camera starts but reboots when accessories activate.|The device requires more power than the negotiated PoE allocation.|Use a compatible power source and supported negotiation.|Test the camera with its full load enabled.
Wrong power adapter|C|A small router repeatedly resets.|The fitted supply rating does not meet the router specification; a correct supply is stable.|Install the specified supply.|Confirm stable operation under load.
UPS battery failure|C|Network equipment resets during a brief outage.|The UPS logs failed battery self-tests and provides no ride-through.|Replace the battery or UPS under the maintenance procedure.|Run the approved UPS load and transfer test.
Thermal shutdown|C|A switch fails during the hottest part of the day.|Temperature alarms precede shutdown; the intake is obstructed.|Restore cooling and clear the obstruction within maintenance procedures.|Monitor temperature and stability under load.
Intermittent NIC hardware fault|R|One PC drops link on multiple known-good ports.|Cable and port swaps do not move the fault; another NIC in the same PC is stable.|Replace the defective NIC after confirming driver health.|Run sustained traffic and monitor link events.
Electromagnetic interference on copper|R|Errors coincide with nearby industrial equipment starting.|CRC bursts correlate with motor starts and disappear on a separated temporary route.|Reroute or replace the affected cabling per the site design.|Compare counters during repeated equipment cycles.
Unidirectional physical link|R|A fiber uplink shows inconsistent reachability.|The receive path works in one direction only; optical and interface tests isolate one strand.|Repair the failed directional path with the link safely isolated.|Verify both directions and restore redundancy.
`,
  'Ethernet & VLANs': `
Wrong access VLAN|F|A workstation cannot reach its intended gateway.|The access port belongs to VLAN 20 while the work order assigns this desk to VLAN 10.|Assign the approved access VLAN.|Verify the intended subnet and preserve the other department.
Missing VLAN on trunk allow list|C|One department loses access across an uplink.|The target VLAN is absent from the uplink allow list while other required VLANs are present.|Add the missing VLAN while retaining the existing required VLANs.|Test both affected and protected VLANs.
VLAN absent from local switch|F|A newly assigned access port is inactive.|The port references a VLAN that is absent from the switch VLAN table.|Create the approved VLAN on the required switches.|Check port state and end-to-end connectivity.
Access port configured as trunk|C|An ordinary workstation is connected to an unintended trunk.|The approved desk profile is access mode but the running configuration is trunk mode.|Apply the documented access-port profile.|Verify untagged client traffic lands in the assigned VLAN.
Trunk configured as access|C|Only one VLAN crosses a new switch uplink.|One uplink end is access mode; the peer is an 802.1Q trunk.|Align both ends with the approved trunk configuration.|Verify all required VLANs across the uplink.
Native VLAN mismatch|C|Untagged traffic crosses into the wrong broadcast domain.|The two trunk endpoints show different native VLAN IDs.|Align the approved native VLAN on both endpoints.|Verify tagged and untagged traffic and clear mismatch alerts.
Port security MAC violation|C|A replaced workstation is blocked.|The port security counter increases and the learned secure MAC belongs to the old workstation.|Update the authorized MAC binding under the port security policy.|Verify the new endpoint and confirm policy enforcement remains active.
Sticky MAC moved to another port|C|A workstation works on its old desk but not its new desk.|Its secure MAC remains bound to the original switch port.|Move the authorized binding as part of the approved desk change.|Confirm the new port works without allowing unrelated endpoints.
BPDU Guard triggered by desk switch|C|A user-installed switch takes a desk port down.|The port is err-disabled and logs BPDUs from the desk connection.|Remove the unauthorized bridge and recover the approved endpoint port.|Verify no further BPDUs or err-disable events.
Broadcast loop|C|A VLAN becomes unusable after a patch change.|Broadcast counters surge; MAC addresses flap between the new links.|Isolate the confirmed redundant loop and restore the approved topology.|Confirm stable MAC learning and normal broadcast levels.
Unexpected spanning-tree root|C|Layer-2 paths change after adding a switch.|The added switch has the winning bridge ID instead of the designated root.|Restore the planned root priorities under change control.|Verify root roles and blocked paths match the design.
Spanning-tree inconsistent port|R|A redundant uplink stops forwarding.|Spanning-tree reports an inconsistency and peer configuration violates the expected topology.|Correct the specific inconsistency before recovering the port.|Verify stable spanning-tree state without creating a loop.
EtherChannel member mismatch|C|One bundle member is suspended.|Its VLAN or channel settings differ from the other members.|Align the member with the approved bundle configuration.|Confirm all intended members bundle successfully.
LACP passive on both ends|C|A negotiated link aggregation group never forms.|Both peers are configured passive and no peer initiates negotiation.|Set at least one approved peer to active.|Verify LACP neighbors and bundled members.
Static channel against LACP peer|C|An aggregate fails after replacing one side.|One peer uses static aggregation and the other expects LACP.|Align the aggregation protocol on both endpoints.|Verify member consistency and failover behavior.
Voice VLAN absent|C|The PC works through a phone but the phone cannot register.|The desk port lacks the documented voice VLAN assignment.|Restore the approved voice VLAN configuration.|Verify phone addressing and call registration while the PC stays online.
LLDP disabled on phone port|R|A phone does not learn its expected network policy.|The approved phone profile depends on LLDP-MED but the port advertises none.|Restore the supported discovery and network-policy configuration.|Verify the phone learns the expected voice policy.
Multicast snooping without querier|R|A multicast stream stops after membership entries expire.|Snooping is enabled; no querier is active and memberships age out.|Restore the designated multicast querier.|Observe membership refresh and sustained group delivery.
Storm-control threshold too low|R|Legitimate bursts cause intermittent loss.|Storm-control drops rise during normal documented workload peaks.|Adjust thresholds from measured traffic and the approved policy.|Retest legitimate bursts and confirm storm protection remains effective.
MAC address flapping from duplicate VM MACs|R|Traffic alternates between two virtual hosts.|The same MAC moves between hypervisor ports; no physical loop is present.|Assign unique approved MAC addresses to the cloned VMs.|Confirm stable MAC learning and reachability to both VMs.
`,
  'Addressing & DHCP': `
Client in wrong IPv4 subnet|F|One workstation cannot reach its assigned gateway.|The client address is outside the work order subnet while its assigned switch VLAN is correct.|Assign a unique usable address in the documented subnet.|Verify local and routed connectivity without changing departments.
Incorrect default gateway|F|Local communication works but remote services fail.|The configured gateway has no owner on the client LAN.|Set the documented router address as the default gateway.|Test the gateway and a remote application.
Missing default gateway|F|A static-addressed endpoint can reach only its own subnet.|Its route table contains no default route and its gateway field is empty.|Configure the approved default gateway.|Verify traffic to a remote subnet.
Subnet mask too broad|F|Some remote addresses are treated as local.|The endpoint uses /16 where the design specifies /24 and sends ARP for remote hosts.|Set the documented mask.|Verify remote traffic is sent through the gateway.
Subnet mask too narrow|F|Nearby hosts appear unreachable.|The endpoint mask excludes hosts that should be on its local subnet.|Apply the documented prefix.|Verify local neighbors and routed destinations.
Duplicate static IPv4 address|C|Two devices have intermittent connectivity.|ARP observations show two MAC addresses claiming the same assigned IP.|Allocate a unique documented address to the conflicting endpoint.|Confirm one owner per IP and stable connections.
DHCP pool exhausted|C|New clients cannot obtain leases.|The scope has zero free addresses and DISCOVER messages receive no lease offer.|Reclaim invalid allocations or expand the approved address plan.|Verify new leases without conflicts.
DHCP service stopped|C|Clients on several scopes cannot renew.|The server is reachable but its DHCP service is stopped and no offers leave it.|Restore the service after checking the failure logs.|Verify the full lease exchange on affected scopes.
Missing DHCP relay|C|Clients on one routed VLAN receive no addresses.|Broadcast discovery stays on that VLAN and its gateway has no relay configured.|Configure the authorized relay destination.|Verify discovery reaches the server and a lease returns.
Incorrect DHCP relay destination|C|One branch cannot obtain leases after server migration.|Its helper address still points to the retired DHCP server.|Update the relay to the authorized current server.|Verify a full lease exchange across the routed path.
Wrong DHCP gateway option|C|Many newly leased clients cannot leave their subnet.|Their leases all contain a router option that disagrees with the subnet design.|Correct the scope router option and renew affected leases.|Verify new leases and off-subnet access.
Wrong DHCP DNS option|C|Clients reach IPs but cannot resolve internal names.|The scope distributes an unintended resolver address.|Correct the scope DNS option.|Renew a test lease and resolve an internal service.
Rogue DHCP server|R|Some clients receive unexpected addresses and gateway values.|Packet captures show competing offers from an unauthorized server.|Isolate the unauthorized server and apply the approved DHCP protection policy.|Verify only authorized offers remain and renew affected clients.
DHCP reservation uses wrong identifier|C|A device never receives its reserved address.|The reservation key differs from the client identifier used in its requests.|Correct the reservation for the actual approved client identifier.|Renew the device and verify the intended allocation.
Static address inside dynamic pool|C|A conflict occurs when a new client joins.|A manually configured printer address is also available in the dynamic scope.|Exclude or reserve the static allocation and clear the actual conflict.|Verify unique addresses through another lease cycle.
DHCP relay blocked by ACL|C|The relay is configured but clients still receive no offers.|ACL counters show DHCP relay traffic dropped between gateway and server.|Permit the required authorized relay traffic.|Capture a successful complete lease exchange.
IPv6 router advertisements blocked|C|IPv6 hosts lack a default route.|The approved router emits RAs but the access path filters them.|Correct the RA filtering policy for the authorized router.|Verify IPv6 prefix and default route installation.
IPv6 duplicate address detection failure|R|A static IPv6 address remains unusable.|The host reports duplicate address detection failure and a neighbor owns that address.|Assign the correct unique address and resolve the conflicting configuration.|Verify DAD succeeds and IPv6 communication works.
Incorrect IPv6 prefix length|C|Some IPv6 neighbors cannot communicate.|A static host prefix differs from the approved on-link prefix.|Correct the host prefix length.|Verify on-link and routed IPv6 traffic.
APIPA after lease failure|F|A workstation has a 169.254 address and no business access.|DHCP discovery receives no offer; the self-assigned address is not the business subnet.|Trace and restore the DHCP path before renewing the lease.|Confirm an authorized lease, gateway, DNS, and application access.
`,
  'DNS & naming': `
Incorrect client resolver|F|A workstation can reach the server IP but names fail.|Its configured resolver address does not belong to the intended DNS server.|Set the authorized DNS server address.|Resolve the service and open it by name.
Incorrect portal A record|F|The portal name resolves but the service fails.|The DNS answer points to a different address than the designated portal server.|Correct the authoritative A record.|Resolve again and verify the expected application endpoint.
Missing authoritative record|F|One service name returns NXDOMAIN.|The authoritative zone contains no record for the approved service name.|Create the approved record after verifying ownership and target.|Query the authority and recursive resolver for the intended answer.
Stale client DNS cache|C|Only one PC resolves an old server address.|The authority and other clients return the new address; this client retains an old cached answer.|Clear the affected cache after confirming the authoritative change.|Resolve again and connect to the current service.
Stale recursive cache|C|An entire resolver population receives an old answer.|The authority is correct but the recursive server retains the prior record within its cache.|Follow the cache expiry or approved invalidation procedure.|Verify refreshed answers from the recursive server.
Incorrect DNS suffix search list|F|Short names fail while fully qualified names work.|The client appends an unrelated suffix to the short name.|Apply the approved suffix search list or use the correct FQDN.|Test the intended short name and FQDN.
Split DNS answer missing internally|C|A service works externally but not inside.|Internal clients query a separate zone that lacks the intended record.|Publish the approved record in the internal view.|Verify internal and external answers serve their intended audiences.
Conditional forwarder points to retired server|C|Names in one partner domain time out.|The conditional forwarder targets a decommissioned resolver.|Update the forwarding destination and reachability policy.|Query several names in the forwarded namespace.
DNS TCP fallback blocked|R|Small answers work but larger queries fail.|UDP responses are truncated and the subsequent TCP/53 connection is blocked.|Permit authorized DNS TCP fallback.|Verify the complete large answer over TCP.
DNS UDP blocked|C|Name lookups time out while server management works.|The path policy drops UDP/53 requests to the approved resolver.|Correct the required resolver access policy.|Verify client queries and responses.
DNSSEC validation failure after rollover|R|A signed domain returns SERVFAIL on validating resolvers.|The published trust chain does not match the current signing material.|Coordinate correction of the DS and DNSKEY chain with the domain owner.|Verify successful validation without disabling DNSSEC.
CNAME loop|R|An alias never resolves to an address.|The alias chain returns to an earlier name.|Correct the alias chain to a valid terminal record.|Resolve the alias and inspect the full chain.
Dangling CNAME|C|A friendly name no longer works after migration.|Its canonical target no longer exists.|Point the alias to the approved current target.|Verify the alias resolves and the application accepts its hostname.
Wrong reverse DNS record|C|Logs identify a server incorrectly.|Forward lookup is correct but the address PTR points to a retired hostname.|Correct the approved reverse record.|Verify forward and reverse results are consistent with the design.
Duplicate host registration|C|A hostname sometimes reaches the wrong machine.|The DNS name has unintended addresses from two separate endpoint registrations.|Remove the unauthorized registration and fix the naming conflict.|Confirm the intended address set and endpoint identity.
Secondary zone transfer denied|R|One DNS server serves outdated records.|Its SOA serial lags and transfer logs show an ACL rejection.|Permit transfers only between the authorized primary and secondary.|Verify serial convergence and consistent responses.
Expired secondary zone|R|A secondary stops serving a zone.|Transfers have failed longer than the configured expiry interval.|Restore authorized transfer connectivity and refresh the zone.|Confirm current serial and authoritative answers.
Wrong delegated name server|R|Only one subdomain cannot be resolved.|The parent delegation points to a server not authoritative for that child.|Correct the delegation with the zone owner.|Trace resolution from the parent to the correct child authority.
Application bypasses enterprise DNS|C|Browser results disagree with command-line DNS.|The browser uses a separate resolver path while the OS uses enterprise DNS.|Apply the approved browser resolver policy.|Verify the application uses the intended namespace and policy.
Negative DNS cache after record creation|R|A newly created name still returns NXDOMAIN to some clients.|The authority has the record but affected caches retain a previous negative answer.|Allow negative-cache expiry or use approved targeted invalidation.|Verify the new record from previously affected clients.
`,
  'Routing & WAN': `
Missing static route|F|A remote subnet is unreachable.|The router has no matching route and no usable default for that destination.|Install the approved route with the correct next hop.|Verify forward and return paths.
Incorrect static next hop|F|A configured route does not deliver traffic.|The route points to an unreachable or incorrect adjacent router.|Correct the next hop from the routing plan.|Verify next-hop reachability and destination traffic.
Missing return route|F|Requests reach a server but replies never return.|The destination side lacks a route to the source subnet.|Restore the authorized return route.|Verify bidirectional traffic from the original source.
More-specific route overrides intended path|C|Only a subset of addresses takes the wrong exit.|A longer matching prefix points to an unintended next hop.|Correct the erroneous more-specific route.|Verify the affected range and surrounding prefixes.
Unexpected preferred default route|C|Internet traffic uses a backup circuit.|The backup default is preferred by the current route selection settings.|Restore the documented route preference and tracking.|Verify normal path and controlled failover.
OSPF area mismatch|C|Two adjacent routers never form an OSPF relationship.|The shared interface area IDs differ.|Align the interface area according to the design.|Verify adjacency and exchanged routes.
OSPF hello timer mismatch|C|An OSPF neighbor remains absent.|Hello and dead intervals differ between directly connected peers.|Align the approved timers.|Verify stable adjacency beyond the dead interval.
OSPF authentication mismatch|C|An OSPF link is up but routes are missing.|Neighbor logs report authentication failure and configured credentials differ.|Align the authorized authentication settings.|Verify adjacency and route exchange without removing authentication.
OSPF passive interface on transit link|C|A router sends no OSPF hellos to its peer.|The transit interface is marked passive.|Remove passive status only from the intended transit interface.|Verify neighbor formation and intended advertisements.
OSPF MTU mismatch|R|Neighbors stall during database exchange.|Interface MTUs differ and database-description exchange does not complete.|Align link MTUs with the supported design.|Verify full adjacency and large-packet forwarding.
Duplicate OSPF router ID|R|Routing becomes unstable after cloning a router configuration.|Two active routers advertise the same router ID.|Assign unique router IDs through a controlled routing change.|Verify stable adjacencies and consistent topology databases.
BGP remote AS mismatch|C|A new BGP session will not establish.|Peer configuration specifies the wrong remote autonomous system.|Correct the peer AS assignment.|Verify session establishment and authorized route exchange.
BGP prefix filter rejects required route|C|A BGP peer is established but one prefix is absent.|Policy evaluation rejects the required prefix at the configured filter.|Update the approved prefix policy with narrow scope.|Verify the desired prefix and continued rejection of unauthorized routes.
BGP next hop unreachable|C|A received BGP route is unusable.|The BGP next-hop address has no resolving route.|Restore the intended next-hop reachability or approved next-hop handling.|Verify route installation and traffic forwarding.
Route redistribution feedback|R|Routes oscillate between routing domains.|The same prefixes return through redistribution without the intended tags or filters.|Restore loop-prevention tags and redistribution policy.|Verify stable origin and path selection.
Policy routing overrides normal route|R|One traffic class follows an unexpected WAN.|A policy route matches that source or application before normal route lookup.|Correct the policy match or next hop under change control.|Test both matched and unmatched traffic classes.
Path MTU discovery black hole|R|Small packets work while larger sessions stall.|Oversized packets fail and required packet-too-big feedback is filtered.|Restore necessary PMTUD feedback and validate the path MTU.|Test large transfers across the affected path.
WAN shaping rate exceeds carrier contract|C|Traffic drops during predictable upload bursts.|Provider policing counters rise because local egress sends faster than the committed service.|Shape to the agreed service profile.|Verify throughput and drops under sustained load.
Carrier handoff VLAN mismatch|C|A new WAN circuit has link but no service.|The carrier requires a handoff VLAN different from the configured tag.|Align the approved handoff tagging with the carrier.|Verify the demarcation and routed service.
Backup route tracking probes wrong target|R|The backup path activates while the primary is usable.|The tracking probe targets a host that no longer answers although the primary path works.|Use an approved representative and reachable tracking target.|Test primary failure and recovery behavior.
`,
  'Wireless': `
Incorrect Wi-Fi passphrase|F|One client cannot authenticate to a personal SSID.|The client log shows key negotiation failure; other clients join using the approved key.|Correct the saved credential through the approved process.|Verify authentication and network access.
Weak signal at coverage edge|F|A client disconnects in one room.|A survey shows insufficient signal and poor signal-to-noise ratio at that location.|Improve the approved AP placement or coverage plan.|Survey and test at the affected location.
Co-channel airtime congestion|C|Wi-Fi slows during busy periods.|Neighboring cells share the channel and channel utilization is high despite clean wired uplinks.|Adjust the channel and capacity plan using survey evidence.|Measure busy-hour airtime and application performance.
Adjacent-channel interference|C|Clients suffer retries near a neighboring radio.|Overlapping channel use correlates with errors on the affected band.|Select a supported non-overlapping channel plan.|Measure retries and usable throughput.
Hidden-node contention|R|Two clients individually work but degrade each other.|Both reach the AP but cannot reliably hear one another and collide under simultaneous load.|Revise cell design or supported contention controls.|Test both clients concurrently.
Excessive channel width|C|Wide channels perform worse in a dense office.|The spectrum plan leaves too few reusable channels and interference spans the wide channel.|Use a narrower width supported by the capacity plan.|Compare aggregate throughput and airtime reuse.
Wrong SSID-to-VLAN mapping|C|A wireless group receives the wrong network policy.|The SSID maps to a different VLAN than its approved service profile.|Correct the SSID VLAN mapping.|Verify client addressing, isolation, and permitted services.
AP uplink missing client VLAN|C|Clients associate but cannot obtain service on one SSID.|The AP uplink trunk does not carry that SSID VLAN.|Restore the required VLAN on the uplink.|Verify DHCP and application access on every required SSID.
RADIUS server unreachable from controller|C|Enterprise Wi-Fi authentication times out.|The controller sends requests but receives no response from the configured authentication server.|Restore the authorized network path and service.|Verify authentication without changing the enterprise security mode.
Expired EAP server certificate|C|Enterprise clients reject authentication after a date boundary.|Client validation logs identify an expired server certificate.|Renew the correct certificate and chain through the approved process.|Verify strict certificate validation and successful authentication.
Incorrect EAP trust configuration|C|Managed clients reject a newly deployed authentication server.|The certificate chain or server name does not match the managed trust profile.|Correct the approved trust profile or server certificate.|Verify authentication with server validation still enforced.
Captive portal session expired|F|A guest is associated but redirected instead of browsing.|The access system shows an expired guest session.|Complete the approved guest reauthorization flow.|Verify authorized access and guest isolation.
Client isolation blocks intended peer service|C|Wireless clients cannot use a local peer device.|The SSID explicitly prevents client-to-client forwarding.|Provide an approved service path or policy exception rather than removing isolation globally.|Verify the intended service and continued guest separation.
DFS radar channel evacuation|R|An AP changes channel and clients briefly disconnect.|Controller logs show a radar event followed by required channel evacuation.|Plan supported channels and coverage for the regulatory behavior.|Verify recovery and coverage during channel changes.
Transmit power imbalance|C|A client sees strong AP signal but uploads fail.|The AP reaches the client while the lower-power client cannot sustain the return path.|Balance cell size and AP power using two-way survey results.|Verify both uplink and downlink at the cell edge.
Sticky roaming client|C|A mobile device stays connected to a distant AP.|The client remains on the old BSSID while a closer cell offers better service.|Tune the supported roaming and cell design for that client population.|Walk-test handoffs with the affected client type.
Unsupported security mode on legacy client|C|An older device cannot join a new SSID.|Its supported authentication capabilities do not include the required SSID mode.|Upgrade the client or use an approved isolated compatibility service.|Verify access without downgrading the main enterprise SSID.
AP regulatory domain mismatch|R|A replacement AP cannot use the planned channels.|Its regulatory configuration or hardware domain differs from the deployment location.|Use correctly approved hardware and regulatory settings.|Verify legal channel operation and coverage.
Mesh backhaul degradation|R|Clients have strong local signal but poor upstream service.|The mesh backhaul has high retries and low capacity while the access radio is healthy.|Improve the backhaul path or provide an approved wired uplink.|Measure end-to-end performance across the backhaul.
Too many low-rate clients consuming airtime|C|A busy WLAN has low throughput without wired congestion.|Airtime analysis shows slow clients consuming a disproportionate share.|Improve coverage and the approved client/rate policy.|Verify service for supported clients and improved airtime use.
`,
  'Security & access': `
ACL denies required application port|F|Ping works but a specific application fails.|The relevant deny counter increments for the application's destination port.|Add the narrowly scoped authorized permit in the correct order.|Test required access and an intentionally denied flow.
ACL applied in wrong direction|C|A new rule has no intended effect.|The ACL is attached to the opposite traffic direction from the planned enforcement point.|Apply the approved policy at the correct interface and direction.|Verify both permitted and blocked test traffic.
Broad deny placed before specific permit|C|An approved exception does not work.|An earlier matching deny prevents evaluation of the later permit.|Correct rule ordering under the policy change process.|Verify the exception without opening unrelated access.
Host firewall blocks inbound service|C|Remote clients fail while local service tests succeed.|The service listens locally; host firewall logs drop the inbound connection.|Permit the authorized service and source scope.|Verify remote access and continued blocking of other traffic.
Stateful firewall sees asymmetric path|R|Sessions fail despite individually allowed routes.|One direction bypasses the firewall, so the return flow has no matching state.|Restore the intended symmetric inspection path.|Verify complete sessions and failover behavior.
NAT rule matches wrong source subnet|C|One internal subnet cannot use the external service.|Translation counters match other subnets but not the affected source range.|Correct the approved NAT source match.|Verify translated sessions from affected and unaffected subnets.
NAT pool exhausted|C|New outbound sessions fail while existing ones continue.|Available translations are exhausted at the configured pool limit.|Restore capacity or correct abnormal session consumption.|Verify new sessions under expected peak load.
Missing NAT exemption for VPN|C|Internal traffic enters a VPN with the wrong source.|The flow is translated before matching the intended protected subnet policy.|Restore the approved VPN NAT exemption.|Verify original source addressing across the tunnel.
VPN phase-one proposal mismatch|C|An IPsec tunnel never establishes its control association.|Peer logs show no common IKE proposal.|Align approved IKE algorithms and parameters.|Verify negotiation without weakening the required policy.
VPN traffic-selector mismatch|C|A tunnel is up but one subnet cannot pass.|The peers disagree on the protected local and remote subnet selectors.|Align authorized traffic selectors.|Verify all approved subnet pairs and rejection outside them.
Expired VPN certificate|C|A previously working tunnel cannot authenticate.|Peer logs show certificate expiry rather than transport failure.|Renew the correct certificate and chain.|Verify authenticated tunnel establishment.
RADIUS shared-secret mismatch|C|A network device reaches AAA but authentication fails.|AAA logs report message authentication failure from that device.|Correct the authorized shared-secret configuration securely.|Verify authentication and accounting from the device.
802.1X authorization assigns wrong VLAN|C|An authenticated endpoint lands in the wrong department.|The RADIUS accept response contains an unintended VLAN attribute.|Correct the role mapping in the approved access policy.|Verify authentication and the intended network assignment.
MAB registration missing|C|A non-802.1X device remains in a restricted network.|The fallback MAC authentication request finds no authorized inventory entry.|Register the approved device through the access process.|Verify the intended restricted or production role.
DHCP snooping trusted uplink missing|C|DHCP offers disappear at the access switch.|Snooping drops server messages arriving on an untrusted authorized uplink.|Trust only the approved DHCP-server-facing path.|Verify valid leases and continued rogue-offer blocking.
Dynamic ARP inspection binding mismatch|R|A static-addressed host cannot reach its gateway.|ARP inspection drops its valid ARP because no matching approved binding exists.|Add the authorized static binding or supported exception.|Verify host access and continued invalid-ARP rejection.
IP source guard blocks moved endpoint|R|A moved client has link but no IP traffic.|Its current port does not match the validated source binding.|Refresh the legitimate binding through the approved access workflow.|Verify only the authorized source is accepted.
Management ACL excludes jump host|C|Administrators cannot reach device management from the approved jump host.|Management access logs deny the jump host source after a policy edit.|Restore the narrow approved management source allowance.|Verify jump-host access and denial from unauthorized sources.
SSH host-key change after authorized replacement|F|An SSH client warns that the server key changed.|The device was replaced and the new key fingerprint is confirmed through the trusted inventory.|Update the saved key only after validating the replacement identity.|Reconnect and verify the expected fingerprint.
NTP skew breaks ticket authentication|R|Domain services reject otherwise valid logins.|Client and authentication server clocks exceed the accepted skew.|Restore the approved time synchronization path.|Verify clock alignment and successful authentication.
`,
  'Applications & services': `
Application service stopped|F|The server responds to ping but the application is unavailable.|No process listens on the intended port and service logs show it stopped.|Restore the service after resolving its recorded failure.|Test the actual application from a client.
Application bound only to loopback|C|The service works on the server but not remotely.|The listening socket is bound to 127.0.0.1 rather than the intended interface.|Bind the approved service endpoint appropriately.|Verify remote access and intended exposure scope.
Incorrect application port|F|A client fails after a service configuration change.|The client targets a different port from the documented listener.|Align the client endpoint with the approved service port.|Test a complete application transaction.
Expired HTTPS certificate|F|Clients reject an HTTPS service.|Certificate inspection shows the presented certificate is expired.|Renew and install the approved certificate and chain.|Verify normal certificate validation succeeds.
HTTPS hostname mismatch|C|A service is reachable but certificate validation fails.|The requested hostname is absent from the certificate's valid names.|Use the correct hostname or deploy the appropriate certificate.|Verify hostname validation with no bypass.
Missing intermediate certificate|C|Some clients reject a certificate that others accept.|The server omits an intermediate and affected clients cannot build the chain.|Install the correct complete server chain.|Validate from a client without a cached intermediate.
Wrong system proxy|C|Only proxy-aware applications fail.|The client proxy configuration points to a retired or unreachable proxy.|Apply the approved proxy settings.|Test required destinations through the intended route.
Proxy bypass missing internal domain|C|Internal applications are mistakenly sent to an external proxy.|The internal namespace is absent from the approved bypass list.|Correct the scoped bypass policy.|Verify internal direct access and external proxy enforcement.
Load-balancer health check uses wrong path|C|Healthy application servers are removed from rotation.|The health probe requests a retired path that returns an error.|Set the approved health endpoint and expected response.|Verify backend health and client transactions.
Load balancer forwards to wrong backend port|C|The virtual service answers but requests fail.|The pool member configuration differs from the actual service listener.|Correct the approved backend port mapping.|Verify each backend and the virtual endpoint.
Application connection pool exhausted|R|Requests time out while network tests remain healthy.|Application metrics show all pool slots occupied and requests waiting.|Resolve leaked or excessive connections and size the pool from evidence.|Verify normal request latency under representative load.
Server disk full blocks service writes|C|A reachable application cannot save transactions.|Service logs show write failures and the required filesystem has no free space.|Recover capacity using the application's retention and recovery procedure.|Verify writes and monitor free space.
NTP server unreachable|F|A device clock drifts after a network change.|Time queries to the configured server receive no response.|Restore access to an approved time source.|Verify synchronization status and offset.
SNMP version mismatch|C|Monitoring cannot poll a device.|The poller and device use incompatible SNMP versions or security profiles.|Align the approved monitoring configuration.|Verify polling without downgrading the required security.
SNMP view excludes required OIDs|R|Some metrics are missing while basic polling succeeds.|The configured view omits the required object subtree.|Extend the approved read view narrowly.|Verify required metrics and restricted access elsewhere.
Syslog destination incorrect|F|Device events never arrive at the collector.|The device sends logs to an old collector address.|Correct the authorized logging destination.|Generate a benign test event and verify receipt.
QoS classifies voice into bulk queue|C|Calls degrade only when uploads saturate the uplink.|Voice packets enter the bulk class instead of the approved priority class.|Correct classification and trust boundaries per the QoS plan.|Test call quality during competing traffic.
SIP signaling works but RTP is blocked|C|Calls connect with no audio.|Signaling succeeds while the authorized media-port range is dropped.|Correct the scoped media path policy.|Verify two-way audio and call teardown.
Multicast TTL too low for routed receivers|R|A stream works locally but not beyond its first router.|Packets arrive with insufficient TTL for the documented receiver path.|Set the approved stream TTL and validate multicast routing.|Verify delivery to intended remote receivers only.
Service dependency unavailable|C|The web front end responds but transactions fail.|Application logs identify an unreachable database dependency while front-end networking is healthy.|Restore the authorized dependency service or path.|Complete an end-to-end transaction, not just a front-end ping.
`,
  'Operations & resilience': `
Wrong device changed|F|A repair has no effect on the reported endpoint.|The edited hostname and serial do not match the work order inventory.|Stop changes, restore any unintended edit, and identify the correct asset.|Verify the intended repair and the accidentally touched device.
Unsaved running configuration lost on reboot|F|A previously fixed issue returns after restarting a device.|Startup configuration lacks the approved changes present before reboot.|Persist the verified configuration using the platform's approved process.|Compare running and startup state and follow the reboot validation plan.
Outdated network diagram|F|The documented path does not match field observations.|Cable tracing and neighbor data identify a topology different from the print.|Validate the actual approved topology and update the record.|Have the corrected path independently checked.
Missing configuration backup|F|A failed device cannot be replaced confidently.|The backup inventory lacks a current verified configuration.|Recover an approved source of truth and restore scheduled verified backups.|Perform a controlled restore validation.
Backup job silently failing|C|Recent configuration changes are absent from backups.|The scheduler runs but authentication errors prevent retrieval.|Repair the authorized backup access and alerting.|Verify a new backup and its readable contents.
Monitoring threshold misconfigured|C|A capacity issue was never alerted.|Measured utilization crossed the policy threshold but the monitor was configured above it.|Align thresholds and duration with the operating policy.|Replay a safe test condition and confirm the expected alert.
Alert routing points to inactive team|C|Critical alerts are generated but nobody responds.|Delivery records show an obsolete escalation destination.|Update the approved ownership and escalation routing.|Send a benign test alert and confirm acknowledgment.
Maintenance suppression left enabled|C|Monitoring stays silent after maintenance.|The affected objects remain suppressed beyond the approved window.|End stale suppression and correct its expiry controls.|Verify current health and restored alert evaluation.
Incorrect monitoring interface selection|C|Capacity reports disagree with the real uplink.|The collector tracks an unused interface index after a hardware change.|Map monitoring to the intended stable interface identity.|Compare counters on the device and dashboard.
Counter reset mistaken for traffic drop|F|A graph shows a sudden impossible negative rate.|The interface counter restarted at reboot and the poller treated it as continuous.|Correct counter-reset handling in the monitoring system.|Verify rate calculations across a controlled reset sample.
Redundant power feeds share one circuit|C|Both power supplies fail during one breaker outage.|The A and B leads trace to the same electrical circuit.|Move to independently approved power feeds with facilities coordination.|Verify feed independence through the approved test plan.
Standby gateway priority incorrect|C|The unexpected router owns the virtual gateway.|Redundancy priority and preemption settings differ from the design.|Restore the approved active/standby preference.|Verify ownership and controlled failover.
Standby gateway tracking missing|R|Clients black-hole traffic after the active router loses its uplink.|The router retains gateway ownership because uplink health is not tracked.|Configure the approved health tracking and priority adjustment.|Test upstream failure and recovery.
HA state synchronization broken|R|Sessions drop during firewall failover despite healthy links.|The HA pair reports failed state synchronization.|Restore the dedicated authorized synchronization path and compatibility.|Verify synchronized state and controlled failover.
Configuration drift between HA peers|C|Failover changes application access unexpectedly.|The peers have different approved policy revisions.|Reconcile configuration using the authoritative version.|Verify parity and behavior on both peers.
Firmware incompatibility in device stack|R|A new stack member never becomes ready.|The member software is incompatible with the stack's supported version set.|Install the approved compatible release using the maintenance plan.|Verify membership, ports, and redundancy.
Expired support entitlement blocks planned update|R|A scheduled recovery cannot obtain the required image.|The required entitlement is absent and the image source cannot be verified.|Resolve the entitlement or approved replacement path with the owner.|Verify lawful trusted image access before scheduling installation.
Change implemented outside approved scope|F|An unrelated department fails during a targeted repair.|The diff contains changes beyond the approved device and VLAN.|Roll back the unintended scope and reassess the planned fix.|Verify both target and protected services.
Rollback plan references stale configuration|C|A failed change cannot be safely reversed using the runbook.|The listed rollback predates later approved changes.|Build a rollback from the verified pre-change baseline.|Validate that it restores required current services.
Incomplete handoff hides temporary workaround|F|The next technician cannot explain an unusual configuration.|A temporary route or bypass exists with no owner, expiry, or ticket note.|Document and review the workaround with the service owner.|Verify its impact and planned removal criteria.
`,
  'Fiber & optical': `
Contaminated connector end face|F|An optical circuit has excess loss after repatching.|Inspection identifies contamination on the disconnected end face.|Inspect, clean with approved tools, and reinspect before reconnecting.|Measure loss and verify the end face meets acceptance criteria.
Unseated optical connector|F|A fiber connection drops after cabinet work.|The connector is not fully latched in its intended adapter.|Seat the correct inspected connector securely.|Verify optical levels and stable service.
Transmit and receive fibers reversed|F|A duplex link has no communication after installation.|Polarity tracing shows transmit connected to transmit rather than the peer receive.|Correct the documented duplex polarity.|Verify both optical receive paths and service.
Single-mode and multimode mismatch|C|A new optical link does not meet its loss budget.|Installed fiber and optics do not match the approved media design.|Use a compatible fiber and transceiver combination.|Measure optical performance against the correct specifications.
Optical wavelength mismatch|C|Two endpoints have light but do not establish a usable link.|The installed transceivers use incompatible wavelengths for the intended link.|Install the approved compatible optics.|Verify wavelength pairing and receive levels.
BiDi transceivers use same side of pair|C|A single-fiber bidirectional circuit will not link.|Both modules transmit on the same wavelength instead of complementary wavelengths.|Install the correct complementary transceiver pair.|Verify transmit and receive wavelengths in both directions.
Receive power below sensitivity|F|An optical receiver reports low light.|Measured receive power is below the module's specified operating range.|Locate and correct excess path loss or redesign the approved budget.|Verify receive power with operating margin.
Receive power above overload limit|C|A short optical link has errors despite strong light.|The receive level exceeds the receiver's specified maximum.|Apply the approved attenuation or compatible optics design.|Verify receive power lies within the supported range.
Macrobend loss|C|Optical loss increases after a tray is closed.|A tight bend violates the cable bend specification; loss improves when corrected.|Restore the specified bend radius and routing.|Measure loss with the enclosure in its normal closed state.
Microbend from excessive tie pressure|R|Loss appears after cable dressing.|A tight restraint compresses the cable and the measured loss changes when relieved.|Use approved supports without excessive compression.|Verify stable optical measurements after redressing.
High-loss fusion splice|C|A span fails its acceptance budget after repair.|Bidirectional testing localizes excessive loss at the new splice.|Reprepare and resplice using the qualified procedure.|Verify splice and end-to-end loss from both directions.
Broken fiber in closure|C|A previously working span is dark.|An OTDR trace ends at the closure and continuity testing isolates the fiber.|Repair the break under the approved outage and splice plan.|Verify continuity, loss, and service restoration.
Wrong splitter port assignment|C|A customer is connected to the wrong optical distribution path.|Plant records and tracing identify a different splitter port from the assigned circuit.|Correct the assignment and records.|Verify the intended customer path and neighboring service.
Splitter loss omitted from budget|F|A planned PON path has insufficient optical margin.|The calculation includes cable loss but omits the installed splitter stages.|Recalculate and redesign the path within the approved optical class.|Verify measured and calculated end-to-end margin.
UPC and APC connector mismatch|C|A patched circuit has high reflection and excess loss.|The mating connector polish types differ.|Use the correct matched connectors and adapters.|Inspect and test loss and reflectance.
Dirty OTDR launch connector|C|Many unrelated fibers show the same near-end anomaly.|The common launch connection fails inspection.|Clean or replace the launch connection and reestablish the reference setup.|Retest known-good fiber and the affected circuit.
Missing OTDR launch fiber|F|The first connection cannot be assessed.|The test setup lacks sufficient launch fiber to move the connection beyond the instrument dead zone.|Use the appropriate launch and receive setup.|Verify both end connections can be evaluated.
OTDR ghost mistaken for real event|R|A trace suggests an event beyond the actual fiber end.|The apparent event repeats a strong reflection pattern and has no matching physical distance.|Confirm with alternate setup and bidirectional measurements before repairing.|Identify the real events without acting on the artifact.
One-direction splice gainer|R|A splice appears to have negative loss.|Opposite-direction measurements differ because of backscatter characteristics.|Use the approved bidirectional averaging method.|Report the combined splice loss rather than a single-direction gainer.
Incorrect power-meter reference|F|Measured insertion loss is implausible across multiple circuits.|The reference setup differs from the approved test method or uses contaminated reference cords.|Reestablish the reference with verified cords and the specified method.|Validate a known-good link before retesting customer fibers.
`,
};
