// CCNA 200-301 question bank.
//
// Shape, domains and v2 tags are documented in bank.js. Every entry is tagged
// for blueprint v2.0 so February 2027 is a filter change rather than a rewrite.
//
// Coverage is checked in tests against the domain weights, so a thin domain
// fails the suite rather than quietly producing a misweighted mock exam.

export const CCNA_BANK = [
  {
    id: "nf-001", domain: "NF", v2: "same", format: "single",
    scenario: "Carving a /24 into subnets for a new branch.",
    prompt: "How many usable host addresses does a /27 subnet provide?",
    choices: [
      { text: "30", correct: true, why: "32 addresses in the block, minus network and broadcast." },
      { text: "32", correct: false, why: "That is the block size, before removing network and broadcast." },
      { text: "62", correct: false, why: "That is a /26." },
      { text: "14", correct: false, why: "That is a /28." },
    ],
    explain: "A /27 leaves 5 host bits, so 2^5 = 32 addresses per block. Subtract the network address and the broadcast address and you get 30 usable. Block size 32 means subnets start at .0, .32, .64, .96 and so on, which is the number to count in rather than doing binary in your head.",
  },
  {
    id: "nf-002", domain: "NF", v2: "same", format: "single",
    scenario: "Reading ipconfig on a Windows host with IPv6 enabled.",
    prompt: "An address beginning fe80:: is what kind of IPv6 address?",
    choices: [
      { text: "Link-local, valid only on that segment", correct: true, why: "fe80::/10, generated automatically, never routed." },
      { text: "Global unicast, routable on the internet", correct: false, why: "Those come from 2000::/3." },
      { text: "Unique local, the IPv6 private range", correct: false, why: "Those are fc00::/7." },
      { text: "Multicast", correct: false, why: "IPv6 multicast is ff00::/8." },
    ],
    explain: "Every IPv6-enabled interface builds a link-local address in fe80::/10 whether or not anything else is configured. Routers never forward it off the link, and it is what neighbor discovery and OSPFv3 adjacencies actually use as the next hop.",
  },
  {
    id: "nf-003", domain: "NF", v2: "same", format: "single",
    scenario: "Explaining switch behaviour to a new hire.",
    prompt: "On a switch with no VLANs configured beyond the default, how many broadcast domains exist?",
    choices: [
      { text: "One, covering every port", correct: true, why: "All ports sit in VLAN 1 by default." },
      { text: "One per port", correct: false, why: "That describes collision domains on a switch." },
      { text: "One per connected device", correct: false, why: "Devices do not create broadcast domains." },
      { text: "Two, one per direction", correct: false, why: "Duplex has no bearing on broadcast domains." },
    ],
    explain: "A switch gives every port its own collision domain, which is why full duplex works. Broadcast domains are a VLAN boundary, so an unconfigured switch is a single broadcast domain. Each VLAN you add creates another, and a router or SVI is what moves traffic between them.",
  },
  {
    id: "nf-004", domain: "NF", v2: "same", format: "single",
    scenario: "Addressing a private network.",
    prompt: "Which range is reserved for private use by RFC 1918?",
    choices: [
      { text: "172.16.0.0 through 172.31.255.255", correct: true, why: "The full block is 172.16.0.0/12." },
      { text: "172.16.0.0 through 172.16.255.255", correct: false, why: "Too narrow; the block runs to 172.31." },
      { text: "172.0.0.0 through 172.255.255.255", correct: false, why: "Too wide; most of 172 is public." },
      { text: "169.254.0.0 through 169.254.255.255", correct: false, why: "That is APIPA link-local, not RFC 1918." },
    ],
    explain: "The three private blocks are 10.0.0.0/8, 172.16.0.0/12, and 192.168.0.0/16. The 172 one catches people because the boundary is 172.16 to 172.31, not all of 172. Anything in 169.254 is a host that gave up on DHCP and assigned itself an address.",
  },
  {
    id: "na-001", domain: "NA", v2: "deeper", format: "single",
    scenario: "Two switches are trunked, and traffic is crossing VLANs that should be separate.",
    prompt: "What does a native VLAN mismatch on a trunk cause?",
    choices: [
      { text: "Traffic from the two native VLANs is bridged together", correct: true, why: "Untagged frames land in whichever VLAN each side calls native." },
      { text: "The trunk goes down immediately", correct: false, why: "It stays up, which is what makes this dangerous." },
      { text: "All VLANs stop crossing the trunk", correct: false, why: "Tagged VLANs keep working normally." },
      { text: "The switch reloads", correct: false, why: "No such behaviour." },
    ],
    explain: "Frames in the native VLAN cross a trunk untagged. If one end calls VLAN 1 native and the other calls VLAN 10 native, each side drops those untagged frames into its own native VLAN, silently joining two networks that were supposed to be isolated. CDP logs the mismatch, and the link stays up throughout, so nothing looks broken.",
  },
  {
    id: "na-002", domain: "NA", v2: "deeper", format: "single",
    scenario: "Bundling two links between switches.",
    prompt: "Which LACP combination forms an EtherChannel?",
    choices: [
      { text: "One side active, the other passive", correct: true, why: "Active initiates, passive answers." },
      { text: "Both sides passive", correct: false, why: "Neither side ever starts negotiation." },
      { text: "One side active, the other set to on", correct: false, why: "Mode on skips LACP entirely and will not negotiate." },
      { text: "One side passive, the other set to on", correct: false, why: "Same problem: on does not speak LACP." },
    ],
    explain: "LACP forms a channel with active/active or active/passive. Passive/passive fails because nobody initiates. Mode on forces the bundle with no negotiation at all, so pairing it with active or passive gives you a mismatch that can loop. Match both ends deliberately rather than assuming.",
  },
  {
    id: "na-003", domain: "NA", v2: "same", format: "single",
    scenario: "Working out which switch became root.",
    prompt: "How is the spanning tree root bridge elected?",
    choices: [
      { text: "Lowest bridge ID, which is priority then MAC address", correct: true, why: "Priority first; the MAC breaks a tie." },
      { text: "Highest bridge ID", correct: false, why: "Lowest wins, not highest." },
      { text: "The switch with the most ports", correct: false, why: "Port count plays no part." },
      { text: "The first switch powered on", correct: false, why: "Boot order plays no part." },
    ],
    explain: "The bridge ID is priority plus MAC address. Default priority is 32768 everywhere, so with no configuration the oldest switch in the closet usually wins on lowest MAC, which is rarely the one you want. Set priority deliberately on your distribution switches instead of leaving it to chance.",
  },
  {
    id: "na-004", domain: "NA", v2: "deeper", format: "single",
    scenario: "An access port takes 30 seconds to pass traffic after a PC boots.",
    prompt: "Which feature fixes the delay on an access port?",
    choices: [
      { text: "PortFast, moving the port straight to forwarding", correct: true, why: "Skips listening and learning on an edge port." },
      { text: "Raising the STP priority", correct: false, why: "Priority affects root election, not port delay." },
      { text: "Turning off the port security", correct: false, why: "Port security has no bearing on STP timers." },
      { text: "Setting the port to trunk", correct: false, why: "That changes VLAN handling, not convergence delay." },
    ],
    explain: "Without PortFast the port walks through listening and learning, roughly 30 seconds, before forwarding. On a port with a single host that wait buys nothing and breaks DHCP for clients that give up early. Apply it only to edge ports, and pair it with BPDU guard so somebody plugging a switch into that jack cannot take out your topology.",
  },
  {
    id: "ipc-001", domain: "IPC", v2: "deeper", format: "single",
    scenario: "Two routers on the same subnet never form an adjacency.",
    prompt: "Which mismatch prevents an OSPF adjacency from forming?",
    choices: [
      { text: "Different hello and dead timers", correct: true, why: "Timers must match for neighbors to form." },
      { text: "Different hostnames", correct: false, why: "Hostnames are cosmetic to OSPF." },
      { text: "Different router models", correct: false, why: "OSPF is an open standard across vendors." },
      { text: "Different interface descriptions", correct: false, why: "Descriptions are local documentation only." },
    ],
    explain: "Neighbors must agree on area ID, hello and dead intervals, subnet and mask, authentication, and stub area flags. Router IDs must be unique rather than matching. An MTU mismatch is the cruel one: neighbors reach EXSTART or EXCHANGE and stall there rather than failing outright, so show ip ospf neighbor is the first command to run.",
  },
  {
    id: "ipc-002", domain: "IPC", v2: "same", format: "single",
    scenario: "Explaining why a gigabit link and a ten gigabit link cost the same.",
    prompt: "What is the default OSPF reference bandwidth?",
    choices: [
      { text: "100 Mbps", correct: true, why: "Cost is reference divided by interface bandwidth." },
      { text: "1 Gbps", correct: false, why: "That is a common manual change, not the default." },
      { text: "10 Gbps", correct: false, why: "Also a manual change on modern networks." },
      { text: "1.544 Mbps", correct: false, why: "That is a T1, unrelated to the reference." },
    ],
    explain: "Cost is 100 Mbps divided by interface bandwidth, with a minimum of 1. So Fast Ethernet, gigabit, and ten gigabit all compute to cost 1, and OSPF cannot tell them apart. Raise it with auto-cost reference-bandwidth, and set the same value on every router in the area or your costs will not agree.",
  },
  {
    id: "ipc-003", domain: "IPC", v2: "same", format: "single",
    scenario: "A packet for 10.1.1.55 arrives with several matching routes present.",
    prompt: "The table holds 10.0.0.0/8, 10.1.0.0/16, and 10.1.1.0/24. Which is used?",
    choices: [
      { text: "10.1.1.0/24, the longest prefix match", correct: true, why: "Most specific route always wins." },
      { text: "10.0.0.0/8, the first learned", correct: false, why: "Learning order is irrelevant." },
      { text: "Whichever has the lowest administrative distance", correct: false, why: "AD only settles ties between sources for the same prefix." },
      { text: "All three, load balanced", correct: false, why: "Different prefix lengths are not equal-cost paths." },
    ],
    explain: "Longest prefix match is decided before administrative distance or metric. AD only comes into play when two protocols offer the same prefix, and metric only when one protocol offers the same prefix twice. Techs reach for AD too early here, which is why a specific static route beats an OSPF-learned summary regardless of what else is configured.",
  },
  {
    id: "ipc-004", domain: "IPC", v2: "same", format: "single",
    scenario: "The same network is learned by two protocols.",
    prompt: "Which source does the router install when a prefix is learned from both a static route and OSPF?",
    choices: [
      { text: "The static route, at administrative distance 1", correct: true, why: "Lower AD is more trusted." },
      { text: "The OSPF route, at 110", correct: false, why: "110 is less trusted than 1." },
      { text: "Both, load balanced", correct: false, why: "Only equal-cost paths from the same source are balanced." },
      { text: "Neither, the route is discarded", correct: false, why: "AD resolves this cleanly." },
    ],
    explain: "Administrative distance ranks how much the router trusts a source: connected 0, static 1, eBGP 20, EIGRP 90, OSPF 110, RIP 120. Lower wins. This is why a hand-typed static route quietly overrides your routing protocol, which is fine when intended and a long outage when somebody forgot it was there.",
  },
  {
    id: "ipc-005", domain: "IPC", v2: "same", format: "single",
    scenario: "Pointing a branch router at its upstream.",
    prompt: "Which command installs a default route toward 203.0.113.1?",
    choices: [
      { text: "ip route 0.0.0.0 0.0.0.0 203.0.113.1", correct: true, why: "All zeros matches anything not matched more specifically." },
      { text: "ip route 203.0.113.1 0.0.0.0 0.0.0.0", correct: false, why: "Arguments are in the wrong order." },
      { text: "ip default-network 203.0.113.1", correct: false, why: "A legacy classful command, not a default route." },
      { text: "ip route 255.255.255.255 0.0.0.0 203.0.113.1", correct: false, why: "That mask and prefix combination matches nothing useful." },
    ],
    explain: "The form is ip route, then destination, then mask, then next hop. A destination and mask of all zeros matches every address, and because it is the shortest possible prefix it is only used when nothing more specific matches. It shows in the table as S*.",
  },
  {
    id: "ipc-006", domain: "IPC", v2: "same", format: "single",
    scenario: "Two routers picked the same OSPF router ID.",
    prompt: "How does a router choose its OSPF router ID when none is configured?",
    choices: [
      { text: "Highest loopback address, then highest active interface address", correct: true, why: "Loopbacks win because they never go down." },
      { text: "Lowest interface address", correct: false, why: "Highest, not lowest." },
      { text: "The MAC address of the first interface", correct: false, why: "OSPF router IDs are dotted-quad, sourced from addresses." },
      { text: "It is assigned by the designated router", correct: false, why: "Each router chooses its own." },
    ],
    explain: "Order is the configured router-id first, then the highest loopback, then the highest active physical interface. Loopbacks are preferred because they never flap. Set it explicitly with the router-id command so your topology does not reshuffle the day someone adds an interface with a higher address.",
  },
  {
    id: "ipc-007", domain: "IPC", v2: "same", format: "single",
    scenario: "Giving hosts a gateway that survives a router failure.",
    prompt: "What does HSRP give the hosts on a segment?",
    choices: [
      { text: "One virtual IP shared by an active and a standby router", correct: true, why: "Hosts point at the virtual address and never change it." },
      { text: "Load balancing across every router at once", correct: false, why: "HSRP is active/standby; only one forwards per group." },
      { text: "Automatic client addressing", correct: false, why: "That is DHCP." },
      { text: "A backup route learned by OSPF", correct: false, why: "FHRP works at the gateway, not in the routing table." },
    ],
    explain: "Hosts get one default gateway address and keep it. The active router answers for the virtual IP and MAC, the standby watches, and if the active fails the standby takes over both, so hosts notice nothing and need no reconfiguration. Routing protocols cannot help here because hosts do not run them.",
  },
  {
    id: "ips-001", domain: "IPS", v2: "same", format: "single",
    scenario: "Reading a NAT translation table.",
    prompt: "What is the inside local address?",
    choices: [
      { text: "The private address of the inside host, as seen inside", correct: true, why: "Inside plus local means the real internal address." },
      { text: "The public address the inside host appears as", correct: false, why: "That is the inside global address." },
      { text: "The address of the outside server", correct: false, why: "That is an outside address." },
      { text: "The router's outside interface address", correct: false, why: "That is often the inside global, not the local." },
    ],
    explain: "Read the two words separately. Inside or outside says which side of the NAT the host physically lives on. Local or global says which side you are looking from. So a workstation at 192.168.1.50 appearing on the internet as 203.0.113.7 has inside local 192.168.1.50 and inside global 203.0.113.7.",
  },
  {
    id: "ips-002", domain: "IPS", v2: "same", format: "single",
    scenario: "One public address serving a whole office.",
    prompt: "What makes PAT able to share a single public address across many hosts?",
    choices: [
      { text: "It tracks a unique source port per session", correct: true, why: "Port numbers disambiguate the return traffic." },
      { text: "It rotates addresses on a timer", correct: false, why: "There is only one address to use." },
      { text: "It compresses the packets", correct: false, why: "Compression has no role in translation." },
      { text: "It assigns each host a public address in turn", correct: false, why: "That is dynamic NAT, which needs a pool." },
    ],
    explain: "PAT, also called NAT overload, rewrites the source address and the source port, then remembers the pairing. Return traffic hits that port and gets mapped back to the right internal host. It is why thousands of hosts fit behind one address, and why inbound connections need an explicit static mapping to work at all.",
  },
  {
    id: "ips-003", domain: "IPS", v2: "deeper", format: "single",
    scenario: "Clients on a VLAN get no address, and the DHCP server sits on another subnet.",
    prompt: "What makes DHCP work across the router?",
    choices: [
      { text: "An ip helper-address on the client-facing interface", correct: true, why: "It relays the broadcast to the server as unicast." },
      { text: "A static route to the DHCP server", correct: false, why: "Routing is already fine; the problem is broadcast." },
      { text: "Enabling proxy ARP", correct: false, why: "Unrelated to DHCP discovery." },
      { text: "Putting the server in the same VLAN", correct: false, why: "That works but is not what the question asks, and it does not scale." },
    ],
    explain: "A DHCP DISCOVER is a broadcast, and routers do not forward broadcasts. ip helper-address on the interface facing the clients catches it and relays it as unicast to the server, filling in the giaddr field so the server knows which scope to answer from. Blueprint v2.0 raises this from configure and verify to troubleshoot, and adds the IOS DHCP server feature alongside it.",
  },
  {
    id: "ips-004", domain: "IPS", v2: "v2only", format: "single",
    scenario: "A name resolves, but to the wrong host.",
    prompt: "Which record type maps a hostname to an IPv4 address?",
    choices: [
      { text: "A", correct: true, why: "The address record, IPv4." },
      { text: "AAAA", correct: false, why: "That is the IPv6 equivalent." },
      { text: "CNAME", correct: false, why: "That aliases one name to another name." },
      { text: "MX", correct: false, why: "That points at mail exchangers." },
    ],
    explain: "A maps a name to an IPv4 address, AAAA to IPv6, CNAME aliases a name to another name, MX handles mail, NS delegates a zone, and PTR does the reverse lookup. V1.1 only asks you to explain what DNS is for. Blueprint v2.0 names the six primary record types and asks you to diagnose issues with them, which means reading command output and identifying the root cause without necessarily fixing it.",
  },
  {
    id: "secf-001", domain: "SECF", v2: "same", format: "single",
    scenario: "Placing an ACL that matches only on source.",
    prompt: "Where does a standard ACL belong?",
    choices: [
      { text: "Close to the destination", correct: true, why: "Matching only source, it would over-block placed early." },
      { text: "Close to the source", correct: false, why: "That is the guidance for extended ACLs." },
      { text: "On the router with the lowest ID", correct: false, why: "Router ID has no bearing on ACL placement." },
      { text: "On every interface in the path", correct: false, why: "That multiplies maintenance with no benefit." },
    ],
    explain: "A standard ACL matches source address only, so placing it near the source would block that source from reaching everything rather than the one destination you meant. Put it near the destination. An extended ACL matches source, destination, protocol and port, so it goes near the source and drops unwanted traffic before it crosses the network.",
  },
  {
    id: "secf-002", domain: "SECF", v2: "same", format: "single",
    scenario: "An ACL with three permit lines is blocking traffic nobody expected.",
    prompt: "What happens to traffic matching none of the entries?",
    choices: [
      { text: "It is denied by the implicit deny at the end", correct: true, why: "Every ACL ends with an unwritten deny any." },
      { text: "It is permitted, since nothing denied it", correct: false, why: "The default is deny, not permit." },
      { text: "It is logged and permitted", correct: false, why: "No logging happens without an explicit log keyword." },
      { text: "It is sent to the CPU for inspection", correct: false, why: "No such behaviour." },
    ],
    explain: "Every access list ends with an invisible deny any. Write three permits and you have denied everything else, which catches people who intend an ACL to block one thing. If you want the rest through, the last line has to be an explicit permit. Adding a final deny any with the log keyword is a common way to see what you are dropping.",
  },
  {
    id: "secf-003", domain: "SECF", v2: "same", format: "single",
    scenario: "A port with port security shut itself down.",
    prompt: "Which violation mode is the default?",
    choices: [
      { text: "Shutdown, putting the port in err-disabled", correct: true, why: "The port stops forwarding until it is cleared." },
      { text: "Protect, dropping quietly", correct: false, why: "That drops offending frames with no notification." },
      { text: "Restrict, dropping and counting", correct: false, why: "That drops, logs, and increments a counter." },
      { text: "Permit, allowing with a warning", correct: false, why: "No such mode exists." },
    ],
    explain: "Shutdown is the default and puts the port into err-disabled, which stays down until you shut and no shut it or errdisable recovery brings it back. Protect drops silently, restrict drops while logging and counting. Silent dropping is the worst of the three to troubleshoot, because the port looks perfectly healthy.",
  },
  {
    id: "secf-004", domain: "SECF", v2: "same", format: "single",
    scenario: "Choosing wireless security for a new office.",
    prompt: "What does WPA3-Personal improve over WPA2-Personal?",
    choices: [
      { text: "It replaces the pre-shared key handshake with SAE", correct: true, why: "SAE resists offline dictionary attacks on captured handshakes." },
      { text: "It doubles the maximum throughput", correct: false, why: "Security standards do not change data rates." },
      { text: "It removes the need for a passphrase", correct: false, why: "Personal mode still uses one." },
      { text: "It encrypts at Layer 3 instead of Layer 2", correct: false, why: "Wireless encryption stays at Layer 2." },
    ],
    explain: "WPA2-Personal lets an attacker capture the four-way handshake and grind the passphrase offline at their leisure. WPA3-Personal uses Simultaneous Authentication of Equals, so a captured exchange gives no material to attack offline and each guess has to be made against the live network. It also gives forward secrecy, so yesterday's capture stays unreadable even if the passphrase leaks later.",
  },
  {
    id: "auto-001", domain: "AUTO", v2: "same", format: "single",
    scenario: "Reading an API response from a controller.",
    prompt: "Which is valid JSON?",
    choices: [
      { text: "{\"vlan\": 10, \"name\": \"data\"}", correct: true, why: "Double-quoted keys, comma separated, no trailing comma." },
      { text: "{vlan: 10, name: data}", correct: false, why: "Keys and string values must be double quoted." },
      { text: "{\"vlan\": 10, \"name\": \"data\",}", correct: false, why: "JSON forbids a trailing comma." },
      { text: "{'vlan': 10, 'name': 'data'}", correct: false, why: "Single quotes are not valid JSON." },
    ],
    explain: "JSON wants double quotes on keys and on string values, commas between pairs and none after the last, and no comments. Numbers, true, false, and null are bare. Single quotes and trailing commas are legal in Python and JavaScript, which is exactly why they slip into hand-written JSON and break the parse.",
  },
  {
    id: "auto-002", domain: "AUTO", v2: "same", format: "single",
    scenario: "Choosing the right REST call to change a setting.",
    prompt: "Which HTTP method is NOT idempotent?",
    choices: [
      { text: "POST", correct: true, why: "Repeating it creates another resource each time." },
      { text: "GET", correct: false, why: "Reading repeatedly changes nothing." },
      { text: "PUT", correct: false, why: "Writing the same full resource twice leaves the same result." },
      { text: "DELETE", correct: false, why: "Deleting something already gone leaves it gone." },
    ],
    explain: "Idempotent means running it again lands you in the same state. GET reads, PUT replaces, DELETE removes, and repeating any of them is harmless. POST creates, so firing it twice gives you two objects. This matters when a script retries after a timeout, which is the usual way duplicate VLANs and duplicate tickets appear.",
  },
  {
    id: "auto-003", domain: "AUTO", v2: "deeper", format: "single",
    scenario: "Comparing configuration management tools.",
    prompt: "What distinguishes Ansible from Puppet and Chef?",
    choices: [
      { text: "It is agentless and pushes over SSH or NETCONF", correct: true, why: "Nothing has to be installed on the managed device." },
      { text: "It is the only one using YAML", correct: false, why: "Format is not the distinguishing trait here." },
      { text: "It runs only on Cisco hardware", correct: false, why: "It is vendor neutral." },
      { text: "It requires a controller appliance", correct: false, why: "A control node is any machine with Ansible installed." },
    ],
    explain: "Ansible pushes from a control node over SSH or NETCONF with no agent on the device, which is why it took hold in networking where you often cannot install software on a switch. Puppet and Chef use agents that pull from a master. Playbooks are YAML. Blueprint v2.0 raises this from identifying capabilities to using Ansible, so expect to read and reason about a playbook.",
  },
  {
    id: "auto-004", domain: "AUTO", v2: "same", format: "single",
    scenario: "Describing a controller-based architecture.",
    prompt: "What does a southbound API connect?",
    choices: [
      { text: "The controller down to the network devices", correct: true, why: "It pushes state into switches and routers." },
      { text: "The controller up to applications", correct: false, why: "That is the northbound API." },
      { text: "One controller to another", correct: false, why: "That is east-west, between peers." },
      { text: "A device to its console port", correct: false, why: "Console access is not an API." },
    ],
    explain: "Picture the controller in the middle. Northbound faces applications and orchestration, usually REST, and is how you ask for an outcome. Southbound faces the devices, using NETCONF, RESTCONF, or OpenFlow, and is how the controller makes it happen. East-west runs between controllers in a cluster.",
  },
  {
    id: "auto-005", domain: "AUTO", v2: "v2only", format: "single",
    scenario: "Writing a prompt that will touch network data.",
    prompt: "Why does data classification belong in a prompt?",
    choices: [
      { text: "It sets how sensitive the data is, driving access and protection", correct: true, why: "Public, private, and confidential call for different handling." },
      { text: "It makes the model respond faster", correct: false, why: "Classification is about handling, not speed." },
      { text: "It compresses the input", correct: false, why: "No compression is involved." },
      { text: "It picks which language the answer uses", correct: false, why: "That is unrelated to classification." },
    ],
    explain: "Blueprint v2.0 adds prompt creation as a foundational AI security topic, covering data classification, output format, persona, and instructions. Classification sorts data by sensitivity so the right access controls and protections apply, which matters when the thing you are about to paste into a model is a running configuration with credentials in it.",
  },
  {
    id: "auto-006", domain: "AUTO", v2: "v2only", format: "single",
    scenario: "Comparing how organisations run their networks.",
    prompt: "Which describes the infrastructure-as-code approach?",
    choices: [
      { text: "A central source of truth, applied by config management tools", correct: true, why: "Device state is defined in version control and pushed." },
      { text: "An engineer using SSH on each device", correct: false, why: "That is device-based management." },
      { text: "A cloud-hosted portal managing devices", correct: false, why: "That is cloud-based management." },
      { text: "A controller loading configuration into devices", correct: false, why: "That is controller-based management." },
    ],
    explain: "Blueprint v2.0 asks you to describe five approaches: device-based, meaning CLI over SSH; automation-based, scripting the CLI with Python and REST; infrastructure-as-code, keeping a central source of truth applied by tools like Ansible; cloud-based, managed from a hosted portal; and controller-based, where software loads configuration into the devices. The distinctions are worth having straight for interviews as much as for the exam.",
  },
  {
    id: "nf-005", domain: "NF", v2: "same", format: "single",
    scenario: "Splitting a /24 for four departments.",
    prompt: "How many subnets does borrowing to /26 create from a /24?",
    choices: [
      { text: "4", correct: true, why: "Two borrowed bits give 2^2 subnets." },
      { text: "2", correct: false, why: "That is one borrowed bit, a /25." },
      { text: "8", correct: false, why: "That is three bits, a /27." },
      { text: "16", correct: false, why: "That is four bits, a /28." },
    ],
    explain: "Going from /24 to /26 borrows two host bits, so 2^2 = 4 subnets of 64 addresses each: .0, .64, .128, .192. Each gives 62 usable hosts. Count subnets with the bits you borrowed and hosts with the bits you left.",
  },
  {
    id: "nf-006", domain: "NF", v2: "same", format: "single",
    scenario: "A customer address is 172.16.45.14 with mask 255.255.240.0.",
    prompt: "What is the network address?",
    choices: [
      { text: "172.16.32.0", correct: true, why: "/20 gives a block of 16 in the third octet." },
      { text: "172.16.45.0", correct: false, why: "That assumes a /24 boundary." },
      { text: "172.16.40.0", correct: false, why: "40 is not a multiple of 16." },
      { text: "172.16.0.0", correct: false, why: "That would be the /16 network." },
    ],
    explain: "255.255.240.0 is /20, leaving 4 subnet bits in the third octet, so the block size there is 16. Subnets run 0, 16, 32, 48. The third octet 45 falls in the block starting at 32, giving network 172.16.32.0 and broadcast 172.16.47.255.",
  },
  {
    id: "nf-007", domain: "NF", v2: "same", format: "single",
    scenario: "Documenting an IPv6 address for a ticket.",
    prompt: "What is 2001:0db8:0000:0000:0000:ff00:0042:8329 in shortest form?",
    choices: [
      { text: "2001:db8::ff00:42:8329", correct: true, why: "Leading zeros dropped, one run of zero groups replaced by ::" },
      { text: "2001:db8:0:0:0:ff00:42:8329", correct: false, why: "Valid, but the zero run can still be collapsed." },
      { text: "2001:db8::ff00::8329", correct: false, why: "Only one :: is allowed per address." },
      { text: "2001:db8:ff00:42:8329::", correct: false, why: "That moves the groups and changes the address." },
    ],
    explain: "Two rules. Drop leading zeros inside each group, so 0db8 becomes db8 and 0042 becomes 42. Then replace one run of consecutive all-zero groups with a double colon. Only one double colon per address, otherwise the length is ambiguous.",
  },
  {
    id: "nf-008", domain: "NF", v2: "same", format: "single",
    scenario: "Explaining a TCP capture to a new hire.",
    prompt: "What is the order of the TCP three-way handshake?",
    choices: [
      { text: "SYN, SYN-ACK, ACK", correct: true, why: "Client offers, server answers, client confirms." },
      { text: "ACK, SYN, SYN-ACK", correct: false, why: "The ACK cannot come first." },
      { text: "SYN, ACK, SYN-ACK", correct: false, why: "The server sends SYN and ACK in one segment." },
      { text: "SYN, SYN, ACK, ACK", correct: false, why: "The server combines its SYN and ACK." },
    ],
    explain: "Client sends SYN with its starting sequence number, server replies with SYN-ACK carrying its own sequence number and acknowledging the client's, and the client sends the final ACK. In a capture, a SYN with no SYN-ACK following it means the far end never answered, which points at a filter or a dead listener rather than a network path problem.",
  },
  {
    id: "nf-009", domain: "NF", v2: "same", format: "single",
    scenario: "A frame arrives for a MAC the switch has never seen.",
    prompt: "What does the switch do?",
    choices: [
      { text: "Floods it out every port in that VLAN except the one it arrived on", correct: true, why: "Unknown unicast flooding." },
      { text: "Drops it and logs the MAC", correct: false, why: "Switches do not drop unknown unicast." },
      { text: "Sends it to the default gateway", correct: false, why: "That is a Layer 3 decision a switch does not make." },
      { text: "Buffers it until the MAC is learned", correct: false, why: "No buffering happens for this." },
    ],
    explain: "With no entry in the MAC address table the switch floods the frame across the VLAN, and the reply teaches it where that MAC lives. This is why a switch works with an empty table on boot. Constant flooding after the table fills usually means MAC flapping or a table being aged or overflowed.",
  },
  {
    id: "nf-010", domain: "NF", v2: "same", format: "single",
    scenario: "Choosing fiber for a 900 metre run between buildings.",
    prompt: "Why is single-mode chosen over multi-mode here?",
    choices: [
      { text: "A narrower core carries one light path with far less dispersion over distance", correct: true, why: "That is what makes long runs viable." },
      { text: "It is cheaper per metre", correct: false, why: "Single-mode optics generally cost more." },
      { text: "It carries power as well as data", correct: false, why: "Neither fiber type delivers power." },
      { text: "It is immune to bend loss", correct: false, why: "All fiber suffers bend loss." },
    ],
    explain: "Multi-mode has a wide core, so light takes multiple paths and they arrive smeared apart, which limits useful distance to a few hundred metres. Single-mode has a core narrow enough for essentially one path, so the pulse stays clean over kilometres. The fiber itself is not the expensive part; the optics are.",
  },
  {
    id: "nf-011", domain: "NF", v2: "same", format: "single",
    scenario: "A server team asks about running several VMs on one box.",
    prompt: "What defines a type 1 hypervisor?",
    choices: [
      { text: "It runs directly on the hardware with no host OS beneath it", correct: true, why: "Bare metal, so less overhead and less to break." },
      { text: "It runs as an application on a desktop OS", correct: false, why: "That is type 2." },
      { text: "It only runs Linux guests", correct: false, why: "Guest OS choice is unrelated to the type." },
      { text: "It requires a controller appliance", correct: false, why: "No controller is implied." },
    ],
    explain: "Type 1 sits on the bare metal and the guests sit on it, which is what runs in data centres. Type 2 runs as a program inside an existing desktop OS, which is what you use on a laptop to lab with. Fewer layers means less overhead and a smaller attack surface.",
  },
  {
    id: "nf-012", domain: "NF", v2: "same", format: "single",
    scenario: "Connecting two switches with an old patch cable.",
    prompt: "What does auto-MDIX do?",
    choices: [
      { text: "Detects the cable type and adapts the port's transmit and receive pairs", correct: true, why: "Straight-through or crossover both work." },
      { text: "Negotiates speed and duplex", correct: false, why: "That is autonegotiation, a separate function." },
      { text: "Powers the far end over the cable", correct: false, why: "That is PoE." },
      { text: "Tests the cable for faults", correct: false, why: "That is TDR, a different feature." },
    ],
    explain: "Historically switch to switch needed a crossover and switch to host a straight-through. Auto-MDIX detects and swaps internally, so either works. Worth knowing it depends on autonegotiation being on, which is why hard-setting speed and duplex on both ends can resurrect an old cabling problem you thought was extinct.",
  },
  {
    id: "na-005", domain: "NA", v2: "deeper", format: "single",
    scenario: "Deciding how to configure a port going to a single desktop.",
    prompt: "What does a trunk port carry that an access port does not?",
    choices: [
      { text: "Traffic for multiple VLANs, tagged with 802.1Q", correct: true, why: "Tags identify which VLAN each frame belongs to." },
      { text: "More bandwidth", correct: false, why: "Trunking does not change link speed." },
      { text: "Routed traffic only", correct: false, why: "Trunks carry Layer 2 frames." },
      { text: "Power for the attached device", correct: false, why: "That is PoE, independent of trunking." },
    ],
    explain: "An access port belongs to one VLAN and sends frames untagged, which is what an ordinary PC expects. A trunk carries many VLANs and tags each frame with its VLAN ID, except the native VLAN which crosses untagged. Putting a PC on a trunk usually means it ignores the tagged traffic and only sees the native VLAN.",
  },
  {
    id: "na-006", domain: "NA", v2: "deeper", format: "single",
    scenario: "Hardening access ports in a public area.",
    prompt: "Why configure switchport mode access explicitly on a user port?",
    choices: [
      { text: "It stops DTP from negotiating the port into a trunk", correct: true, why: "A negotiated trunk would expose every VLAN." },
      { text: "It doubles the port speed", correct: false, why: "Mode has no effect on speed." },
      { text: "It enables PortFast automatically", correct: false, why: "PortFast is a separate command." },
      { text: "It assigns an IP address to the port", correct: false, why: "Access ports are Layer 2." },
    ],
    explain: "Left on dynamic auto or dynamic desirable, a port can be talked into trunking by whatever is plugged in, which hands an attacker every VLAN on the switch. Setting mode access and adding switchport nonegotiate shuts that down. It is one of the cheapest hardening steps on a switch.",
  },
  {
    id: "na-007", domain: "NA", v2: "same", format: "single",
    scenario: "A desk phone with a PC plugged into its back port.",
    prompt: "What does a voice VLAN let the switch do on one access port?",
    choices: [
      { text: "Carry tagged phone traffic and untagged PC traffic separately", correct: true, why: "Two VLANs on what is still an access port." },
      { text: "Give the port twice the bandwidth", correct: false, why: "Bandwidth is unchanged." },
      { text: "Route between the phone and the PC", correct: false, why: "A switch port makes no routing decision." },
      { text: "Power the phone", correct: false, why: "That is PoE, configured separately." },
    ],
    explain: "The phone tags its own voice traffic into the voice VLAN while the PC behind it sends untagged frames that land in the data VLAN. It keeps voice separate for QoS and security without a second cable run, and it is why a port can look like an access port and still show two VLANs.",
  },
  {
    id: "na-008", domain: "NA", v2: "same", format: "single",
    scenario: "A lightweight access point joins a controller.",
    prompt: "What does CAPWAP do between the AP and the WLC?",
    choices: [
      { text: "Tunnels control and client data between them", correct: true, why: "Control on UDP 5246, data on 5247." },
      { text: "Assigns the AP an IP address", correct: false, why: "That is DHCP." },
      { text: "Encrypts the wireless air link", correct: false, why: "That is WPA2 or WPA3 at the radio." },
      { text: "Elects a root access point", correct: false, why: "No such election exists here." },
    ],
    explain: "A lightweight AP holds almost no configuration and builds a CAPWAP tunnel to the controller, with control traffic on UDP 5246 and client data on 5247. The controller handles the SSIDs, policy, and roaming. So an AP that cannot reach its WLC serves nothing at all, which makes WLC reachability the first thing to check on a dead AP.",
  },
  {
    id: "na-009", domain: "NA", v2: "same", format: "single",
    scenario: "A branch AP keeps serving clients after the WAN to head office drops.",
    prompt: "Which AP mode allows that?",
    choices: [
      { text: "FlexConnect, switching client traffic locally", correct: true, why: "It keeps serving when the controller is unreachable." },
      { text: "Local mode, tunnelling everything to the WLC", correct: false, why: "That stops when the tunnel drops." },
      { text: "Monitor mode", correct: false, why: "Monitor mode serves no clients at all." },
      { text: "Sniffer mode", correct: false, why: "Sniffer mode only captures for analysis." },
    ],
    explain: "In local mode every client frame rides the CAPWAP tunnel back to the controller, so a WAN outage takes the wireless with it. FlexConnect lets the AP switch client traffic straight onto the local VLAN and keep authenticating, which is exactly what a small branch on a fragile circuit needs.",
  },
  {
    id: "na-010", domain: "NA", v2: "same", format: "single",
    scenario: "Comparing RSTP with legacy spanning tree.",
    prompt: "Which port role is new in RSTP?",
    choices: [
      { text: "Alternate, a ready backup to the root port", correct: true, why: "It can take over without waiting out the timers." },
      { text: "Root", correct: false, why: "Classic STP has root ports." },
      { text: "Designated", correct: false, why: "Classic STP has designated ports." },
      { text: "Disabled", correct: false, why: "Not a new RSTP role." },
    ],
    explain: "RSTP adds alternate and backup roles, which is where the speed comes from. An alternate port already knows it is the next best path to the root, so on failure it can move to forwarding in about a second instead of walking through the 30 to 50 seconds of listening and learning that classic STP needs.",
  },
  {
    id: "na-011", domain: "NA", v2: "same", format: "single",
    scenario: "Planning VLANs on a new switch.",
    prompt: "Why is leaving management traffic in VLAN 1 discouraged?",
    choices: [
      { text: "It is the default everywhere, so any unconfigured port lands in it", correct: true, why: "That exposes management to whatever gets plugged in." },
      { text: "VLAN 1 cannot be routed", correct: false, why: "It routes like any other VLAN." },
      { text: "VLAN 1 has a lower MTU", correct: false, why: "MTU is unrelated to VLAN number." },
      { text: "VLAN 1 is reserved for voice", correct: false, why: "Voice VLANs are assigned, not fixed." },
    ],
    explain: "Every port ships in VLAN 1 and it is the default native VLAN on trunks, so anything plugged into an unconfigured port shares a broadcast domain with your management interfaces. Move management to a dedicated VLAN, change the native VLAN to an unused one, and prune VLAN 1 from trunks where you can.",
  },
  {
    id: "na-012", domain: "NA", v2: "deeper", format: "single",
    scenario: "An access port has to serve a wireless access point.",
    prompt: "Which combination does an AP typically need?",
    choices: [
      { text: "PoE for power, and a trunk if it serves multiple SSIDs mapped to VLANs", correct: true, why: "Power plus VLAN carriage." },
      { text: "PoE only, always on an access port", correct: false, why: "An autonomous AP with several SSIDs needs a trunk." },
      { text: "A crossover cable and a static MAC entry", correct: false, why: "Neither is required." },
      { text: "A routed port with an IP address", correct: false, why: "APs attach at Layer 2." },
    ],
    explain: "Blueprint v2.0 gathers access VLANs, trunking, EtherChannel and PoE into one topic and asks you to match the features to the endpoint type. An AP usually wants power over the cable, and a trunk when several SSIDs map to separate VLANs. A lightweight AP tunnelling to a WLC can sit on an access port instead, because the VLAN separation happens at the controller.",
  },
  {
    id: "ipc-008", domain: "IPC", v2: "same", format: "single",
    scenario: "Three OSPF routers share a broadcast segment.",
    prompt: "How is the designated router chosen?",
    choices: [
      { text: "Highest OSPF priority, then highest router ID", correct: true, why: "Priority first, router ID breaks the tie." },
      { text: "Lowest router ID", correct: false, why: "Highest wins for DR election." },
      { text: "The first router to boot, always", correct: false, why: "Boot order matters only because DR elections are not preemptive." },
      { text: "The router with the most interfaces", correct: false, why: "Interface count plays no part." },
    ],
    explain: "Priority defaults to 1 everywhere, so the highest router ID usually decides. Priority 0 takes a router out of the running entirely, which is how you keep a small branch box from becoming DR. The election is not preemptive: a better router arriving later waits for the current DR to fail.",
  },
  {
    id: "ipc-009", domain: "IPC", v2: "same", format: "single",
    scenario: "OSPF hellos are going out of an interface facing only PCs.",
    prompt: "What does passive-interface do?",
    choices: [
      { text: "Stops hellos on that interface while still advertising its subnet", correct: true, why: "The network stays in the database, neighbours cannot form." },
      { text: "Removes the subnet from OSPF entirely", correct: false, why: "The subnet is still advertised." },
      { text: "Shuts the interface down", correct: false, why: "The interface keeps forwarding normally." },
      { text: "Blocks all routing traffic through the interface", correct: false, why: "Transit traffic is unaffected." },
    ],
    explain: "The subnet keeps being advertised to the rest of the area, but OSPF stops sending hellos out of it, so nothing can form an adjacency there. On any interface facing only end hosts this is what you want: it cuts pointless multicast and removes a path for someone to inject routes from a user port.",
  },
  {
    id: "ipc-010", domain: "IPC", v2: "same", format: "single",
    scenario: "Reading show ip route on a branch router.",
    prompt: "What does the code O IA mean?",
    choices: [
      { text: "An OSPF route learned from another area", correct: true, why: "Inter-area, crossing an area border router." },
      { text: "An OSPF route redistributed from another protocol", correct: false, why: "That shows as E1 or E2." },
      { text: "An inactive OSPF route", correct: false, why: "No such code." },
      { text: "An OSPF route with an invalid metric", correct: false, why: "No such code." },
    ],
    explain: "O is intra-area, learned inside your own area. O IA crossed an ABR from another area. O E1 and O E2 came in through redistribution from outside OSPF, with E2 keeping a fixed external cost and E1 adding the internal cost along the way. E2 is the default and catches people when two exit points look equally good.",
  },
  {
    id: "ipc-011", domain: "IPC", v2: "same", format: "single",
    scenario: "Providing a backup path that stays out of the table until needed.",
    prompt: "How is a floating static route built?",
    choices: [
      { text: "With an administrative distance higher than the primary route's", correct: true, why: "It installs only when the better route disappears." },
      { text: "With a higher metric than the primary", correct: false, why: "Metric only breaks ties within one protocol." },
      { text: "By adding the permanent keyword", correct: false, why: "That keeps a route in regardless of interface state." },
      { text: "By shutting down the backup interface", correct: false, why: "A shut interface carries nothing." },
    ],
    explain: "Give the backup static route an AD above the protocol you are backing up, so 120 to sit behind OSPF's 110. The router prefers OSPF while it has the route, and the static one drops in when OSPF loses it. Leave it at the default AD of 1 and it overrides OSPF permanently, which is the classic way a backup circuit becomes the primary without anyone noticing.",
  },
  {
    id: "ipc-012", domain: "IPC", v2: "same", format: "single",
    scenario: "Two equal paths to the same network.",
    prompt: "What does a router do with two OSPF routes of identical cost?",
    choices: [
      { text: "Installs both and load balances across them", correct: true, why: "Equal-cost multipath, four routes by default." },
      { text: "Picks the one learned first", correct: false, why: "Learning order is not the tiebreaker." },
      { text: "Picks the lower next-hop address", correct: false, why: "No such rule for equal-cost paths." },
      { text: "Drops both as a conflict", correct: false, why: "Equal paths are not a conflict." },
    ],
    explain: "Equal-cost paths from the same protocol both install and the router balances across them, four by default and configurable with maximum-paths. Balancing is per destination by default rather than per packet, which keeps flows from arriving out of order. Unequal-cost balancing is an EIGRP feature, not an OSPF one.",
  },
  {
    id: "ipc-013", domain: "IPC", v2: "same", format: "single",
    scenario: "Designing a multi-area OSPF deployment.",
    prompt: "What is required of area 0?",
    choices: [
      { text: "Every other area must connect to it", correct: true, why: "It is the backbone all inter-area traffic crosses." },
      { text: "It must contain every router", correct: false, why: "Only ABRs and backbone routers sit in it." },
      { text: "It must use the lowest router IDs", correct: false, why: "Router IDs are unrelated to area design." },
      { text: "It must be a single subnet", correct: false, why: "The backbone can hold many subnets." },
    ],
    explain: "OSPF is a hub and spoke at the area level. Area 0 is the backbone and every other area attaches to it through an area border router, so inter-area traffic always transits the backbone. Two non-backbone areas connected only to each other cannot exchange routes, which is what a virtual link exists to patch.",
  },
  {
    id: "ipc-014", domain: "IPC", v2: "same", format: "single",
    scenario: "Reading a route with administrative distance 0.",
    prompt: "Which route source has an AD of 0?",
    choices: [
      { text: "A directly connected network", correct: true, why: "Nothing is more trustworthy than a live local interface." },
      { text: "A static route", correct: false, why: "Static routes are 1." },
      { text: "An OSPF route", correct: false, why: "OSPF is 110." },
      { text: "An eBGP route", correct: false, why: "eBGP is 20." },
    ],
    explain: "Directly connected is 0 and cannot be beaten, which is why you cannot route around a local subnet with a static route. Static is 1, eBGP 20, EIGRP 90, OSPF 110, IS-IS 115, RIP 120. A route with AD 255 is considered unusable and never installs.",
  },
  {
    id: "ipc-015", domain: "IPC", v2: "same", format: "single",
    scenario: "Writing a static route out of a multi-access Ethernet interface.",
    prompt: "Why specify a next-hop address rather than only an exit interface?",
    choices: [
      { text: "On Ethernet the router would otherwise have to ARP for every destination", correct: true, why: "It cannot tell which neighbour to send to." },
      { text: "Exit interfaces are not supported on Ethernet", correct: false, why: "They are supported, just problematic." },
      { text: "It halves the administrative distance", correct: false, why: "AD is unaffected." },
      { text: "It enables load balancing", correct: false, why: "Load balancing needs multiple routes." },
    ],
    explain: "On a point-to-point link there is only one other end, so an exit interface alone is fine. On Ethernet the router does not know which of many neighbours should receive the traffic, so it proxy-ARPs for each destination and builds an enormous ARP table, or fails outright. Name the next hop, or name both.",
  },
  {
    id: "ips-005", domain: "IPS", v2: "same", format: "single",
    scenario: "Checking time sources before troubleshooting logs.",
    prompt: "What does a lower NTP stratum number mean?",
    choices: [
      { text: "Closer to the reference clock", correct: true, why: "Stratum 1 is directly attached to it." },
      { text: "Less accurate", correct: false, why: "Lower is more accurate, not less." },
      { text: "A faster polling interval", correct: false, why: "Stratum says nothing about polling." },
      { text: "A higher priority for routing", correct: false, why: "NTP has nothing to do with routing." },
    ],
    explain: "Stratum 0 is the reference clock itself, an atomic or GPS source. Stratum 1 is directly attached to it, stratum 2 syncs from stratum 1, and so on. Every hop adds error. It matters because correlating logs across devices is impossible when their clocks disagree, which is the first thing to check during an incident.",
  },
  {
    id: "ips-006", domain: "IPS", v2: "same", format: "single",
    scenario: "Tuning how much a switch logs.",
    prompt: "Which syslog severity level is the most severe?",
    choices: [
      { text: "0, emergency", correct: true, why: "Lower numbers are more severe." },
      { text: "7, debugging", correct: false, why: "7 is the least severe and the most verbose." },
      { text: "1, alert", correct: false, why: "Severe, but 0 is above it." },
      { text: "5, notification", correct: false, why: "Mid-range and routine." },
    ],
    explain: "Levels run 0 emergency, 1 alert, 2 critical, 3 error, 4 warning, 5 notification, 6 informational, 7 debugging. Setting a level captures that level and everything more severe, so logging at 4 gives you warnings through emergencies. Leaving a device at 7 in production floods the log and buries the thing you needed.",
  },
  {
    id: "ips-007", domain: "IPS", v2: "same", format: "single",
    scenario: "Choosing how devices report to the monitoring system.",
    prompt: "What distinguishes an SNMP inform from a trap?",
    choices: [
      { text: "An inform is acknowledged by the receiver and resent if not", correct: true, why: "Traps are fire and forget." },
      { text: "An inform is encrypted, a trap is not", correct: false, why: "Encryption comes from SNMPv3, not the message type." },
      { text: "An inform is sent by the manager", correct: false, why: "Both are sent by the agent." },
      { text: "An inform carries no data", correct: false, why: "Both carry variable bindings." },
    ],
    explain: "A trap is sent once with no confirmation, so a dropped packet means the event is gone. An inform waits for an acknowledgement and retransmits, which costs more memory and traffic but survives a lossy path. For alerts you cannot afford to miss, informs are worth the overhead.",
  },
  {
    id: "ips-008", domain: "IPS", v2: "same", format: "single",
    scenario: "Marking voice traffic across the campus.",
    prompt: "Which DSCP value is the usual marking for voice payload?",
    choices: [
      { text: "EF, expedited forwarding", correct: true, why: "Low latency, low jitter, low loss queue." },
      { text: "AF11", correct: false, why: "A lower-priority assured forwarding class." },
      { text: "CS1, scavenger", correct: false, why: "That is the deprioritised class." },
      { text: "Default, best effort", correct: false, why: "Voice would be treated like bulk traffic." },
    ],
    explain: "Voice payload is marked EF, decimal 46, and voice signalling usually CS3. EF maps to a priority queue that is serviced first with a strict bandwidth ceiling. Marking matters only if every device in the path trusts and honours it, so a single switch clearing DSCP on ingress undoes the whole design.",
  },
  {
    id: "secf-005", domain: "SECF", v2: "same", format: "single",
    scenario: "A rogue DHCP server appeared on a user VLAN.",
    prompt: "How does DHCP snooping stop it?",
    choices: [
      { text: "Only trusted ports may send DHCP server messages", correct: true, why: "Offers from untrusted ports are dropped." },
      { text: "It blocks all DHCP on the VLAN", correct: false, why: "Legitimate DHCP keeps working." },
      { text: "It assigns static addresses instead", correct: false, why: "Snooping does not assign addresses." },
      { text: "It shuts down the VLAN", correct: false, why: "No such behaviour." },
    ],
    explain: "Ports facing users are untrusted by default, so a DHCP OFFER or ACK arriving from one gets dropped. The uplink toward the genuine server is marked trusted. It also builds a binding table of address to MAC to port, which dynamic ARP inspection and IP source guard then rely on, so snooping is the foundation for the rest.",
  },
  {
    id: "secf-006", domain: "SECF", v2: "same", format: "single",
    scenario: "Defending against ARP poisoning on an access layer.",
    prompt: "What does dynamic ARP inspection check each ARP reply against?",
    choices: [
      { text: "The DHCP snooping binding table", correct: true, why: "Address, MAC and port must agree." },
      { text: "The routing table", correct: false, why: "ARP is Layer 2; routing is not consulted." },
      { text: "The MAC address table", correct: false, why: "That records where MACs were seen, not which IP owns them." },
      { text: "The running configuration", correct: false, why: "Bindings are dynamic, not configured." },
    ],
    explain: "DAI intercepts ARP on untrusted ports and verifies the sender's address and MAC against the snooping binding table, dropping anything that disagrees. That kills the gratuitous ARP an attacker uses to claim the gateway address. It depends on DHCP snooping being on, so statically addressed hosts need a manual ARP ACL or they get blocked.",
  },
  {
    id: "secf-007", domain: "SECF", v2: "same", format: "single",
    scenario: "Choosing between RADIUS and TACACS+ for device administration.",
    prompt: "What makes TACACS+ the better fit for managing network devices?",
    choices: [
      { text: "It separates authentication from authorization and encrypts the whole payload", correct: true, why: "Per-command authorization becomes possible." },
      { text: "It uses UDP for lower overhead", correct: false, why: "TACACS+ uses TCP port 49." },
      { text: "It is an open standard and RADIUS is not", correct: false, why: "RADIUS is the open standard here." },
      { text: "It supports more simultaneous users", correct: false, why: "Capacity is not the distinction." },
    ],
    explain: "TACACS+ runs over TCP 49, encrypts the entire payload, and keeps the three A's separate, so you can authorize individual commands per role. RADIUS uses UDP, encrypts only the password field, and merges authentication with authorization. So TACACS+ for device administration, RADIUS for network access such as 802.1X.",
  },
  {
    id: "secf-008", domain: "SECF", v2: "same", format: "single",
    scenario: "Reviewing an old switch configuration.",
    prompt: "Why replace enable password with enable secret?",
    choices: [
      { text: "enable secret stores a hash rather than recoverable text", correct: true, why: "Type 7 encoding is trivially reversible." },
      { text: "enable secret allows longer passwords", correct: false, why: "Length limits are similar." },
      { text: "enable password only works on routers", correct: false, why: "Both work on routers and switches." },
      { text: "enable secret enables SSH", correct: false, why: "SSH needs crypto keys and transport settings." },
    ],
    explain: "enable password is stored in clear or under type 7 encoding, which is reversible in seconds by tools that have existed for decades. enable secret stores a hash, and modern IOS offers type 8 and 9 which are far harder to attack than the old type 5. If both are configured, the secret wins, and the plaintext one is still sitting there for anyone reading the config.",
  },
  {
    id: "secf-009", domain: "SECF", v2: "same", format: "single",
    scenario: "Inserting a line into an existing named ACL.",
    prompt: "What makes a named ACL easier to maintain than a numbered one?",
    choices: [
      { text: "Entries can be removed or inserted by sequence number", correct: true, why: "No need to rebuild the whole list." },
      { text: "It is evaluated faster", correct: false, why: "Evaluation is the same." },
      { text: "It supports more entries", correct: false, why: "Capacity is not the difference." },
      { text: "It applies to all interfaces automatically", correct: false, why: "It still has to be applied per interface." },
    ],
    explain: "In named ACL configuration mode you can delete one line by its sequence number or insert a new line between two existing ones. On a classic numbered ACL, removing a single line historically meant removing the whole list, which is how people wiped an ACL on a live device and dropped traffic while retyping it.",
  },
  {
    id: "auto-007", domain: "AUTO", v2: "same", format: "single",
    scenario: "A script calls a controller API and gets back 401.",
    prompt: "What does that status mean?",
    choices: [
      { text: "Authentication failed or was not supplied", correct: true, why: "Credentials or token are the problem." },
      { text: "The resource does not exist", correct: false, why: "That is 404." },
      { text: "The request succeeded", correct: false, why: "Success codes are 2xx." },
      { text: "The server hit an internal error", correct: false, why: "That is 5xx." },
    ],
    explain: "The families are worth knowing cold: 2xx succeeded, 3xx redirect, 4xx the client got it wrong, 5xx the server failed. 401 means unauthenticated, 403 means authenticated but not permitted, 404 means the path is wrong. Telling 401 from 403 saves you hunting a token problem that is actually a permissions problem.",
  },
  {
    id: "auto-008", domain: "AUTO", v2: "same", format: "single",
    scenario: "Reading an Ansible playbook for the first time.",
    prompt: "What data format are playbooks written in?",
    choices: [
      { text: "YAML", correct: true, why: "Indentation-based, human readable." },
      { text: "XML", correct: false, why: "NETCONF uses XML, playbooks do not." },
      { text: "JSON", correct: false, why: "Ansible consumes JSON but playbooks are YAML." },
      { text: "CSV", correct: false, why: "Not a configuration format." },
    ],
    explain: "Playbooks are YAML, where indentation defines structure and tabs are forbidden, which is the usual first error. YAML and JSON describe the same shapes, so a playbook maps onto the JSON an API returns. Blueprint v2.0 raises Ansible from identifying capabilities to using it, so being able to read a playbook and say what it changes is the bar.",
  },
  {
    id: "nf-013", domain: "NF", v2: "same", format: "order",
    scenario: "Walking a new hire down the stack.",
    prompt: "Put the encapsulation steps in order from the application downward.",
    steps: [
      "Data handed down from the application",
      "Transport adds a header, making a segment",
      "Network adds addressing, making a packet",
      "Data link adds a header and trailer, making a frame",
      "Physical transmits it as bits on the medium",
    ],
    explain: "Each layer wraps what it was handed and adds its own header. The names matter because they tell a troubleshooter which layer they are looking at: a capture showing frames but no packets means Layer 2 is moving and Layer 3 is not. Going up the far side, each layer strips its own header back off.",
  },
  {
    id: "nf-014", domain: "NF", v2: "same", format: "multi",
    scenario: "Using /29 subnets for point-to-point links between routers.",
    prompt: "Which TWO are true of a /29? (Choose two.)",
    choices: [
      { text: "It provides 6 usable host addresses", correct: true, why: "8 addresses minus network and broadcast." },
      { text: "Its block size is 8", correct: true, why: "Subnets fall on multiples of 8." },
      { text: "It provides 8 usable host addresses", correct: false, why: "That ignores network and broadcast." },
      { text: "Its block size is 6", correct: false, why: "Block size is always a power of two." },
      { text: "It cannot be used on point-to-point links", correct: false, why: "It is a common choice for them." },
    ],
    explain: "A /29 leaves 3 host bits, so 8 addresses per block and 6 usable. Subnets start at 0, 8, 16, 24. It wastes four addresses on a link that needs two, which is why /31 exists for point-to-point links and gives you exactly two usable addresses with no broadcast.",
  },
  {
    id: "nf-015", domain: "NF", v2: "same", format: "single",
    scenario: "Documenting a point-to-point link on 10.10.10.0/29.",
    prompt: "What is the broadcast address of that subnet?",
    choices: [
      { text: "10.10.10.7", correct: true, why: "Last address in a block of 8." },
      { text: "10.10.10.8", correct: false, why: "That is the next subnet's network address." },
      { text: "10.10.10.6", correct: false, why: "That is the last usable host." },
      { text: "10.10.10.255", correct: false, why: "That would be the /24 broadcast." },
    ],
    explain: "Block size 8 means the subnet runs .0 through .7. Network .0, usable .1 through .6, broadcast .7, and the next subnet starts at .8. Finding the broadcast is always the address one below the next subnet, which is faster than counting up from the network.",
  },
  {
    id: "nf-016", domain: "NF", v2: "same", format: "single",
    scenario: "A gigabit link shows rising late collisions and poor throughput.",
    prompt: "What does a late collision usually indicate?",
    choices: [
      { text: "A duplex mismatch between the two ends", correct: true, why: "One side half duplex, the other full." },
      { text: "A failing power supply", correct: false, why: "Power problems drop the link entirely." },
      { text: "An oversubscribed uplink", correct: false, why: "Congestion shows as output drops, not late collisions." },
      { text: "A VLAN mismatch", correct: false, why: "VLAN problems do not produce collisions." },
    ],
    explain: "A normal collision happens inside the first 64 bytes. A late collision happens after that, which on a modern link means one end is transmitting whenever it likes while the other still expects to listen first. Hard-setting speed and duplex on one end only is the usual cause, because the other end then falls back to half duplex.",
  },
  {
    id: "nf-017", domain: "NF", v2: "same", format: "single",
    scenario: "A host builds its own IPv6 interface identifier.",
    prompt: "What does EUI-64 do with the MAC address?",
    choices: [
      { text: "Inserts FFFE in the middle and flips the seventh bit", correct: true, why: "48 bits become the 64-bit interface identifier." },
      { text: "Hashes it into 64 bits", correct: false, why: "No hashing is involved." },
      { text: "Pads it with zeros", correct: false, why: "The inserted value is FFFE, not zeros." },
      { text: "Discards it and uses a random value", correct: false, why: "That describes privacy addressing, a different mechanism." },
    ],
    explain: "Split the 48-bit MAC in half, insert FFFE between the halves to reach 64 bits, then invert the seventh bit of the first byte. The tell is FFFE sitting in the middle of an address, which immediately tells you the host derived it from its MAC rather than getting it from DHCPv6 or privacy extensions.",
  },
  {
    id: "nf-018", domain: "NF", v2: "same", format: "single",
    scenario: "Specifying cable for a 10 Gbps run to a new closet.",
    prompt: "Which copper category is specified for 10GBASE-T at the full 100 metres?",
    choices: [
      { text: "Cat6a", correct: true, why: "Rated for 10 Gbps over the full distance." },
      { text: "Cat5e", correct: false, why: "Specified for 1 Gbps at 100 m." },
      { text: "Cat3", correct: false, why: "Suitable for 10 Mbps and voice." },
      { text: "Cat6", correct: false, why: "Carries 10 Gbps only over a shorter run, around 55 m." },
    ],
    explain: "Cat5e is the 1 Gbps workhorse. Cat6 can do 10 Gbps but only to roughly 55 metres, and less in dense bundles because of crosstalk. Cat6a has tighter crosstalk specification and carries 10GBASE-T the full 100 metres, which is why it is the safe specification for new horizontal cabling.",
  },
  {
    id: "na-013", domain: "NA", v2: "same", format: "match",
    scenario: "Sorting out which switch feature does what.",
    prompt: "Match each switch feature to what it does.",
    pairs: [
      { left: "PortFast", right: "Moves an edge port straight to forwarding, skipping the STP wait" },
      { left: "BPDU guard", right: "Err-disables a port that receives a BPDU, keeping rogue switches out" },
      { left: "Root guard", right: "Stops a port from accepting a superior BPDU that would move the root" },
      { left: "Port security", right: "Limits which and how many MAC addresses a port will learn" },
    ],
    explain: "These four get confused because they all protect the access layer. PortFast is about speed, BPDU guard and root guard are about protecting your topology from what gets plugged in, and port security is about which hosts may use the port. PortFast and BPDU guard belong together on every user-facing port.",
  },
  {
    id: "na-014", domain: "NA", v2: "same", format: "multi",
    scenario: "VLAN 20 traffic is not reaching the far switch.",
    prompt: "Which TWO are required for VLAN 20 to cross a trunk? (Choose two.)",
    choices: [
      { text: "VLAN 20 must exist in the VLAN database on both switches", correct: true, why: "A switch drops traffic for a VLAN it does not have." },
      { text: "VLAN 20 must be in the trunk's allowed list on both ends", correct: true, why: "Pruning it on either end stops it." },
      { text: "VLAN 20 must be the native VLAN", correct: false, why: "Tagged VLANs cross without being native." },
      { text: "Both switches must use the same STP priority", correct: false, why: "Priority affects root election, not VLAN carriage." },
      { text: "The trunk must be an EtherChannel", correct: false, why: "A single link trunks fine." },
    ],
    explain: "Two independent things have to be true, and people usually check one. The VLAN must be defined on each switch, and it must be permitted on the trunk at both ends. show interfaces trunk lists both the allowed VLANs and the ones actually active, which answers the whole question in one command.",
  },
  {
    id: "na-015", domain: "NA", v2: "same", format: "single",
    scenario: "Planning 2.4 GHz coverage across an office floor.",
    prompt: "Which channels are non-overlapping in the 2.4 GHz band?",
    choices: [
      { text: "1, 6, and 11", correct: true, why: "The only three that do not overlap in North America." },
      { text: "1, 5, and 9", correct: false, why: "These overlap; spacing needs five channels." },
      { text: "2, 7, and 12", correct: false, why: "Channel 12 is unavailable in some regulatory domains." },
      { text: "Any three, since the radios negotiate", correct: false, why: "Radios do not negotiate channel overlap away." },
    ],
    explain: "Each 2.4 GHz channel is 22 MHz wide with centres 5 MHz apart, so only 1, 6, and 11 avoid stepping on each other. Neighbouring APs on channels 2 and 4 interfere without ever showing as an error, just as slow wireless. The 5 GHz band has many more non-overlapping channels, which is the better reason to move clients there.",
  },
  {
    id: "na-016", domain: "NA", v2: "same", format: "single",
    scenario: "A port went err-disabled after a violation.",
    prompt: "What brings it back?",
    choices: [
      { text: "shutdown then no shutdown, or errdisable recovery", correct: true, why: "The port stays down until cleared." },
      { text: "Waiting for the STP timers to expire", correct: false, why: "STP does not clear err-disable." },
      { text: "Reseating the cable", correct: false, why: "The port stays err-disabled regardless of the cable." },
      { text: "Clearing the MAC address table", correct: false, why: "That does not change port state." },
    ],
    explain: "Err-disable is deliberate and sticky, so the port stays down until an operator clears it or errdisable recovery is configured with a timer. That is the point: the switch wants a human to notice. show interfaces status err-disabled tells you which ports and the reason, which matters because port security, BPDU guard, and link flap all land in the same state.",
  },
  {
    id: "na-017", domain: "NA", v2: "same", format: "single",
    scenario: "Authenticating users before granting network access on a wired port.",
    prompt: "In 802.1X, what role does the switch play?",
    choices: [
      { text: "Authenticator, relaying credentials to the authentication server", correct: true, why: "It gates the port but does not decide." },
      { text: "Supplicant, supplying the credentials", correct: false, why: "That is the client device." },
      { text: "Authentication server, validating credentials", correct: false, why: "That is the RADIUS server." },
      { text: "It plays no role and simply forwards", correct: false, why: "The switch enforces the port state." },
    ],
    explain: "Three roles: the supplicant is the client, the authenticator is the switch holding the port closed to everything but EAPOL, and the authentication server is RADIUS making the actual decision. The switch never validates anything itself, which is why an unreachable RADIUS server locks everyone out unless you configure a fallback.",
  },
  {
    id: "na-018", domain: "NA", v2: "deeper", format: "single",
    scenario: "Reading show interfaces trunk during a VLAN problem.",
    prompt: "What does the line listing VLANs in spanning tree forwarding state tell you?",
    choices: [
      { text: "Which allowed VLANs are actually passing traffic on that trunk", correct: true, why: "Allowed and active are different lists." },
      { text: "Which VLANs exist on the switch", correct: false, why: "That is show vlan brief." },
      { text: "Which VLANs are configured for voice", correct: false, why: "Voice VLANs are shown per access port." },
      { text: "Which VLANs have an SVI", correct: false, why: "That is show ip interface brief." },
    ],
    explain: "The command prints several lists: allowed VLANs, allowed and active in the management domain, and the ones in spanning tree forwarding state. A VLAN can be allowed but absent from that last list because it does not exist on the switch or STP is blocking it. Comparing the lists usually finds the fault in one command.",
  },
  {
    id: "ipc-016", domain: "IPC", v2: "deeper", format: "order",
    scenario: "Watching an adjacency come up.",
    prompt: "Put the OSPF neighbor states in order.",
    steps: [
      "Down, no hellos heard yet",
      "Init, a hello was received but this router was not listed in it",
      "2-Way, both routers see each other and DR election happens",
      "Exstart, the two agree who leads the database exchange",
      "Exchange, database descriptions are swapped",
      "Loading, missing link-state records are requested",
      "Full, the databases match",
    ],
    explain: "Knowing the order turns a stuck adjacency into a diagnosis. Stuck in Init means your hellos are arriving and theirs are not, so look at one-way filtering or an access list. Stuck in Exstart or Exchange is the classic MTU mismatch. Sitting at 2-Way on a broadcast segment is normal for two routers that are both non-DR.",
  },
  {
    id: "ipc-017", domain: "IPC", v2: "same", format: "match",
    scenario: "Reading administrative distances during a route problem.",
    prompt: "Match each route source to its default administrative distance.",
    pairs: [
      { left: "Directly connected", right: "0" },
      { left: "Static route", right: "1" },
      { left: "EIGRP internal", right: "90" },
      { left: "OSPF", right: "110" },
      { left: "RIP", right: "120" },
    ],
    explain: "Lower is more trusted, and the number only matters when two sources offer the same prefix. The gap between static at 1 and OSPF at 110 is why a forgotten static route silently wins for years. External EIGRP is 170, eBGP is 20, and 255 means the route is considered unusable and never installs.",
  },
  {
    id: "ipc-018", domain: "IPC", v2: "same", format: "single",
    scenario: "One router connects several VLANs over a single trunk to a switch.",
    prompt: "What does router-on-a-stick require on the router?",
    choices: [
      { text: "Subinterfaces, each with encapsulation dot1Q and an address", correct: true, why: "One subinterface per VLAN being routed." },
      { text: "One physical interface per VLAN", correct: false, why: "That is the design router-on-a-stick avoids." },
      { text: "An SVI for each VLAN", correct: false, why: "SVIs live on a Layer 3 switch, not a router." },
      { text: "A static route for each VLAN", correct: false, why: "Connected subnets need no static routes." },
    ],
    explain: "Each subinterface gets encapsulation dot1Q with its VLAN ID and an address that becomes that VLAN's gateway. The switch port facing the router has to be a trunk carrying those VLANs. It is cheap and it works, with the limit that all inter-VLAN traffic crosses one physical link in both directions.",
  },
  {
    id: "ipc-019", domain: "IPC", v2: "deeper", format: "single",
    scenario: "Two routers sit at EXSTART and never reach FULL.",
    prompt: "What is the usual cause?",
    choices: [
      { text: "An MTU mismatch between the interfaces", correct: true, why: "Database description packets cannot be exchanged." },
      { text: "Different OSPF process IDs", correct: false, why: "Process IDs are locally significant." },
      { text: "Different hostnames", correct: false, why: "Hostnames do not affect OSPF." },
      { text: "Mismatched bandwidth statements", correct: false, why: "That changes cost, not adjacency." },
    ],
    explain: "Neighbors exchange their MTU in the database description packets and refuse to proceed if they disagree, so they stall at EXSTART or EXCHANGE instead of failing cleanly. It appears after someone enables jumbo frames on one side or a sub-interface inherits a different MTU. Process IDs genuinely do not need to match, which is worth remembering because people chase them first.",
  },
  {
    id: "ipc-020", domain: "IPC", v2: "same", format: "single",
    scenario: "Enabling OSPF on 192.168.4.0/24.",
    prompt: "Which wildcard mask matches that network in the network statement?",
    choices: [
      { text: "0.0.0.255", correct: true, why: "Zeros must match, ones are free." },
      { text: "255.255.255.0", correct: false, why: "That is the subnet mask, not the wildcard." },
      { text: "0.0.255.255", correct: false, why: "That would match a /16." },
      { text: "0.0.0.0", correct: false, why: "That matches exactly one address." },
    ],
    explain: "A wildcard is the inverse of the subnet mask: 0 bits must match and 1 bits are ignored. A /24 becomes 0.0.0.255. Using 0.0.0.0 with a specific address is a precise and common way to enable OSPF on exactly one interface, which is often clearer than a broad network statement.",
  },
  {
    id: "ipc-021", domain: "IPC", v2: "same", format: "single",
    scenario: "Configuring HSRP so the stronger router leads.",
    prompt: "A router with higher priority joins a working group and does not take over. Why?",
    choices: [
      { text: "Preempt is not configured", correct: true, why: "Without it, the current active keeps the role." },
      { text: "Its priority is being ignored", correct: false, why: "Priority is read, but preempt governs takeover." },
      { text: "HSRP does not support priority", correct: false, why: "Priority is central to HSRP." },
      { text: "The virtual IP is wrong", correct: false, why: "A wrong virtual IP breaks forwarding, not election." },
    ],
    explain: "HSRP is deliberately non-preemptive by default, so whoever is active stays active even when a better router appears. Add the preempt keyword and the higher-priority router takes over on arrival. Without preempt, a router that reboots comes back as standby, which sometimes surprises people after maintenance.",
  },
  {
    id: "ipc-022", domain: "IPC", v2: "same", format: "single",
    scenario: "A Layer 3 switch routes between VLANs.",
    prompt: "What is an SVI?",
    choices: [
      { text: "A virtual interface giving a VLAN a routable address on the switch", correct: true, why: "interface vlan 10 becomes that VLAN's gateway." },
      { text: "A physical uplink to the router", correct: false, why: "That is a routed port or trunk." },
      { text: "A tunnel to a remote site", correct: false, why: "Tunnels are a separate feature." },
      { text: "A backup switch supervisor", correct: false, why: "Unrelated to interfaces." },
    ],
    explain: "interface vlan 10 gives the switch an address inside VLAN 10, and with ip routing enabled it becomes the gateway for that VLAN. Traffic between VLANs then stays inside the switch at hardware speed rather than crossing a trunk to a router and back, which is why this replaced router-on-a-stick wherever the budget allows.",
  },
  {
    id: "ips-009", domain: "IPS", v2: "same", format: "match",
    scenario: "Reading a firewall rule set.",
    prompt: "Match each service to its well-known port.",
    pairs: [
      { left: "SSH", right: "TCP 22" },
      { left: "DNS", right: "UDP and TCP 53" },
      { left: "HTTPS", right: "TCP 443" },
      { left: "SNMP", right: "UDP 161" },
      { left: "Syslog", right: "UDP 514" },
      { left: "NTP", right: "UDP 123" },
    ],
    explain: "These come up constantly in ACLs and captures. DNS is the one worth noting: queries go over UDP 53, and it falls back to TCP 53 for large responses and zone transfers, so an ACL permitting only UDP breaks resolution in ways that look intermittent.",
  },
  {
    id: "ips-010", domain: "IPS", v2: "same", format: "single",
    scenario: "A customer needs their web server reachable from the internet.",
    prompt: "Which NAT type fits?",
    choices: [
      { text: "Static NAT, a fixed one-to-one mapping", correct: true, why: "The same public address always reaches that server." },
      { text: "PAT, sharing one address by port", correct: false, why: "Inbound sessions have no existing translation to match." },
      { text: "Dynamic NAT from a pool", correct: false, why: "The mapping would change, breaking DNS." },
      { text: "No NAT is needed", correct: false, why: "A private address is unreachable from outside." },
    ],
    explain: "Outbound PAT builds its translation when the inside host starts the session. An inbound connection has no such entry, so it gets dropped. Static NAT creates a permanent mapping in both directions, which is what lets a DNS record point at a stable address. Port forwarding is the same idea narrowed to one port.",
  },
  {
    id: "ips-011", domain: "IPS", v2: "same", format: "single",
    scenario: "Replacing Telnet on the management VLAN.",
    prompt: "What does SSH require that Telnet does not?",
    choices: [
      { text: "A hostname, a domain name, and generated crypto keys", correct: true, why: "The key pair is what encrypts the session." },
      { text: "A dedicated management VLAN", correct: false, why: "Good practice, but not required." },
      { text: "A RADIUS server", correct: false, why: "Local accounts work fine." },
      { text: "A static route to the client", correct: false, why: "Normal routing suffices." },
    ],
    explain: "Set a hostname and ip domain-name, then crypto key generate rsa, because the key is named after host plus domain. Add transport input ssh on the vty lines and a local or AAA login. Telnet sends everything including the password in clear text, so anyone capturing on the path owns the device.",
  },
  {
    id: "ips-012", domain: "IPS", v2: "same", format: "single",
    scenario: "Choosing between shaping and policing on a WAN circuit.",
    prompt: "What does shaping do that policing does not?",
    choices: [
      { text: "Buffers excess traffic and sends it later", correct: true, why: "It delays rather than discards." },
      { text: "Drops traffic above the rate", correct: false, why: "That is policing." },
      { text: "Marks traffic with DSCP", correct: false, why: "That is classification and marking." },
      { text: "Encrypts the traffic", correct: false, why: "Neither encrypts." },
    ],
    explain: "Policing enforces a rate by dropping or remarking what exceeds it, so bursts are lost. Shaping queues the excess and releases it at the configured rate, so bursts are delayed instead. Shaping suits TCP traffic that would otherwise retransmit, and it is the right choice on the customer side of a circuit whose provider polices.",
  },
  {
    id: "secf-010", domain: "SECF", v2: "same", format: "multi",
    scenario: "Securing a closet with several unused switch ports.",
    prompt: "Which TWO steps reduce the risk from unused ports? (Choose two.)",
    choices: [
      { text: "Administratively shut them down", correct: true, why: "A down port carries nothing." },
      { text: "Place them in an unused VLAN with no routing", correct: true, why: "Anything plugged in reaches nothing." },
      { text: "Set them to dynamic desirable", correct: false, why: "That invites trunk negotiation, making it worse." },
      { text: "Leave them in VLAN 1", correct: false, why: "VLAN 1 often carries management traffic." },
      { text: "Enable PortFast on them", correct: false, why: "PortFast speeds them up rather than securing them." },
    ],
    explain: "Shut the port and park it in a black-hole VLAN, so an unplanned connection gets nothing even if someone later enables the port without thinking. Leaving ports in VLAN 1 on dynamic auto is the default state and the worst one, because a laptop running the right software can negotiate a trunk and reach every VLAN.",
  },
  {
    id: "secf-011", domain: "SECF", v2: "same", format: "match",
    scenario: "Sorting out attack terminology for a security briefing.",
    prompt: "Match each attack to its description.",
    pairs: [
      { left: "Phishing", right: "Tricking a person into giving up credentials or running something" },
      { left: "Denial of service", right: "Exhausting a resource so legitimate users cannot be served" },
      { left: "On-path attack", right: "Sitting between two parties and relaying or altering their traffic" },
      { left: "Brute force", right: "Trying credentials repeatedly until one works" },
    ],
    explain: "The distinction that matters operationally is which control stops each one. Phishing is answered by training and multifactor authentication, denial of service by rate limiting and upstream scrubbing, on-path by encryption and dynamic ARP inspection, and brute force by lockouts and key-based authentication.",
  },
  {
    id: "secf-012", domain: "SECF", v2: "same", format: "single",
    scenario: "Applying an extended ACL to block traffic from a branch.",
    prompt: "Applying it inbound on the interface facing the source does what?",
    choices: [
      { text: "Filters the traffic before the router makes a routing decision", correct: true, why: "It is dropped as early as possible." },
      { text: "Filters after routing, on the way out", correct: false, why: "That is an outbound ACL." },
      { text: "Filters traffic in both directions", correct: false, why: "An ACL applies to one direction per interface." },
      { text: "Has no effect until a route exists", correct: false, why: "Inbound filtering happens before routing." },
    ],
    explain: "Inbound is evaluated as the packet arrives, before the routing lookup, so denied traffic costs the router almost nothing. Outbound is evaluated after routing, on the way out of the chosen interface. Direction is per interface, so blocking a conversation both ways takes two applications, and reversing source and destination in the second one.",
  },
  {
    id: "secf-013", domain: "SECF", v2: "same", format: "single",
    scenario: "Reviewing an authentication design.",
    prompt: "Which pair represents two different authentication factors?",
    choices: [
      { text: "A password and a code from a hardware token", correct: true, why: "Something you know plus something you have." },
      { text: "A password and a PIN", correct: false, why: "Both are something you know." },
      { text: "A fingerprint and a retina scan", correct: false, why: "Both are something you are." },
      { text: "Two passwords of different lengths", correct: false, why: "Still one factor used twice." },
    ],
    explain: "The three factors are something you know, something you have, and something you are. Multifactor means drawing from different categories, so a password plus a token qualifies and a password plus a PIN does not. This is why an attacker with a stolen password list is stopped by a token and unaffected by a second password.",
  },
  {
    id: "auto-009", domain: "AUTO", v2: "same", format: "match",
    scenario: "Mapping API calls onto what they do.",
    prompt: "Match each HTTP method to its usual action on a resource.",
    pairs: [
      { left: "GET", right: "Read the resource without changing it" },
      { left: "POST", right: "Create a new resource" },
      { left: "PUT", right: "Replace an existing resource in full" },
      { left: "PATCH", right: "Modify part of an existing resource" },
      { left: "DELETE", right: "Remove the resource" },
    ],
    explain: "These line up with create, read, update, and delete. The distinction worth carrying is PUT replacing the whole object against PATCH changing a field, because a PUT missing fields quietly wipes them. POST is the one that is not idempotent, so a retried POST gives you two of something.",
  },
  {
    id: "auto-010", domain: "AUTO", v2: "deeper", format: "single",
    scenario: "Explaining why a playbook can be run twice safely.",
    prompt: "What does idempotent mean for a configuration management run?",
    choices: [
      { text: "Running it again leaves the device in the same state", correct: true, why: "It changes only what does not already match." },
      { text: "It runs faster the second time", correct: false, why: "Speed is not the property." },
      { text: "It rolls back on failure", correct: false, why: "That is transactional behaviour, a different idea." },
      { text: "It runs on every device at once", correct: false, why: "That is parallelism." },
    ],
    explain: "The tool compares desired state with actual state and acts only on the difference, so running a playbook ten times gives the same result as running it once. That is what makes automation safe to re-run after a partial failure, and it is the practical difference between a configuration management tool and a script that blindly pastes commands.",
  },
  {
    id: "auto-011", domain: "AUTO", v2: "same", format: "single",
    scenario: "Arguing for automation over hand configuration.",
    prompt: "What is the main operational benefit of managing devices from a central source of truth?",
    choices: [
      { text: "Configuration stays consistent and drift becomes visible", correct: true, why: "Every device matches a definition you can review." },
      { text: "Devices need less memory", correct: false, why: "Resource use is unchanged." },
      { text: "Links run faster", correct: false, why: "Automation does not change throughput." },
      { text: "Routing converges sooner", correct: false, why: "Convergence is a protocol matter." },
    ],
    explain: "Hand configuration produces snowflakes: forty switches that were the same on day one and differ by year three, with nobody sure which difference is deliberate. A central definition makes the intended state reviewable and drift detectable, and it means a new switch is provisioned from the same source rather than from memory.",
  },
  {
    id: "auto-012", domain: "AUTO", v2: "same", format: "single",
    scenario: "Reading a controller dashboard that flags a failing link before users notice.",
    prompt: "Which describes predictive analytics in network operations?",
    choices: [
      { text: "Spotting trends in telemetry to flag a problem before it causes an outage", correct: true, why: "Acts on patterns in collected data." },
      { text: "Generating configuration text from a prompt", correct: false, why: "That is generative AI." },
      { text: "Encrypting telemetry in transit", correct: false, why: "That is transport security." },
      { text: "Replacing the routing protocol", correct: false, why: "Analytics does not forward traffic." },
    ],
    explain: "Predictive analytics watches collected telemetry for patterns that historically preceded failures, such as a slowly rising error rate on an optic, and raises it while there is still time to act. Blueprint v1.1 added AI and machine learning at this level. Version 2.0 goes further, adding prompt construction and agentic AI that pulls telemetry and drives troubleshooting itself.",
  },
];
