// Type-it deck: IOS commands and hard facts, typed from memory.
//
// Commands lead because they are the muscle memory the Field console
// demands, and because typing one from nothing is a harder and more useful
// test than recognising it among four options.
//
// accept lists the abbreviations IOS itself would take, so "sh ip int br"
// is as right as the long form. Anything else is wrong, including a
// command that would work but is not what was asked.

export const RECALL_DECK = [
  // ---------- verification ----------
  { id: 'cmd-ospf-nei', domain: 'IPC', kind: 'command', prompt: 'Show the OSPF neighbors and their adjacency state.',
    answer: 'show ip ospf neighbor', accept: ['sh ip ospf nei', 'sh ip ospf neighbor', 'show ip ospf nei'],
    note: 'The first command for any OSPF problem. FULL is healthy; stuck in EXSTART usually means an MTU mismatch.' },
  { id: 'cmd-route', domain: 'IPC', kind: 'command', prompt: 'Show the routing table.',
    answer: 'show ip route', accept: ['sh ip route', 'sh ip ro'],
    note: 'Read the code letter first: C connected, S static, O OSPF, and an asterisk marks the default.' },
  { id: 'cmd-int-brief', domain: 'NF', kind: 'command', prompt: 'Show every interface with its address and up/down state on one line each.',
    answer: 'show ip interface brief', accept: ['sh ip int br', 'sh ip int brief', 'show ip int brief', 'sh ip interface brief'],
    note: 'Status is Layer 1, protocol is Layer 2. Up/down points at the far end or encapsulation; administratively down means someone typed shutdown.' },
  { id: 'cmd-vlan-brief', domain: 'NA', kind: 'command', prompt: 'Show the VLANs on a switch and which access ports belong to each.',
    answer: 'show vlan brief', accept: ['sh vlan br', 'sh vlan brief', 'show vlan br'],
    note: 'Trunk ports are not listed here, which catches people. Use show interfaces trunk for those.' },
  { id: 'cmd-trunk', domain: 'NA', kind: 'command', prompt: 'Show which ports are trunking and which VLANs each one carries.',
    answer: 'show interfaces trunk', accept: ['sh int trunk', 'sh interfaces trunk', 'show int trunk'],
    note: 'Compare the allowed list with the forwarding list. A VLAN that is allowed but not forwarding is missing on the switch or blocked by STP.' },
  { id: 'cmd-stp', domain: 'NA', kind: 'command', prompt: 'Show the spanning tree state, including the root bridge and port roles.',
    answer: 'show spanning-tree', accept: ['sh spanning-tree', 'sh span', 'show span'],
    note: 'Look for "This bridge is the root" to confirm which switch won the election.' },
  { id: 'cmd-ether', domain: 'NA', kind: 'command', prompt: 'Show a one-line summary of every EtherChannel and its member ports.',
    answer: 'show etherchannel summary', accept: ['sh etherchannel summary', 'sh eth sum', 'sh etherchannel sum'],
    note: 'The flags matter: P means bundled, I means standalone, and a standalone member usually means a negotiation mismatch.' },
  { id: 'cmd-run', domain: 'NF', kind: 'command', prompt: 'Show the configuration currently running in memory.',
    answer: 'show running-config', accept: ['sh run', 'show run', 'sh running-config'],
    note: 'This is the live configuration and is lost on reload unless it is saved.' },
  { id: 'cmd-save', domain: 'NF', kind: 'command', prompt: 'Save the running configuration so it survives a reload.',
    answer: 'copy running-config startup-config', accept: ['copy run start', 'write memory', 'wr', 'write', 'wr mem'],
    note: 'Forgetting this is how a working fix disappears after a power cut.' },
  { id: 'cmd-cdp', domain: 'NA', kind: 'command', prompt: 'Show the Cisco devices directly connected to this one.',
    answer: 'show cdp neighbors', accept: ['sh cdp nei', 'sh cdp neighbors', 'show cdp nei'],
    note: 'Add detail to see the neighbor\'s address and software version. LLDP is the vendor-neutral equivalent.' },
  { id: 'cmd-mac', domain: 'NA', kind: 'command', prompt: 'Show which MAC addresses the switch has learned on which ports.',
    answer: 'show mac address-table', accept: ['sh mac address-table', 'sh mac add', 'show mac add'],
    note: 'How you find which port a device is plugged into when all you have is its MAC.' },
  { id: 'cmd-psec', domain: 'SECF', kind: 'command', prompt: 'Show port security status and violation counts for every secured port.',
    answer: 'show port-security', accept: ['sh port-security', 'sh port-sec', 'show port-sec'],
    note: 'Add interface and a port name to see the learned addresses and the violation mode on one port.' },

  // ---------- interface configuration ----------
  { id: 'cmd-access', domain: 'NA', kind: 'command', prompt: 'On an interface, make it an access port.',
    answer: 'switchport mode access', accept: ['sw mode access', 'switchport mode acc', 'sw mo acc'],
    note: 'Setting this explicitly stops DTP negotiating the port into a trunk.' },
  { id: 'cmd-access-vlan', domain: 'NA', kind: 'command', prompt: 'On an access port, put it in VLAN 10.',
    answer: 'switchport access vlan 10', accept: ['sw access vlan 10', 'sw acc vlan 10', 'switchport acc vlan 10'],
    note: 'If VLAN 10 does not exist yet, the switch creates it and warns you.' },
  { id: 'cmd-trunk-mode', domain: 'NA', kind: 'command', prompt: 'On an interface, make it a trunk.',
    answer: 'switchport mode trunk', accept: ['sw mode trunk', 'sw mo tr', 'switchport mode tr'],
    note: 'Older switches supporting ISL need switchport trunk encapsulation dot1q first.' },
  { id: 'cmd-trunk-allowed', domain: 'NA', kind: 'command', prompt: 'On a trunk, allow only VLANs 10 and 20.',
    answer: 'switchport trunk allowed vlan 10,20', accept: ['sw trunk allowed vlan 10,20', 'switchport trunk allowed vlan 10, 20'],
    note: 'This replaces the list. To add one VLAN without wiping the rest, use allowed vlan add.' },
  { id: 'cmd-native', domain: 'NA', kind: 'command', prompt: 'On a trunk, set the native VLAN to 99.',
    answer: 'switchport trunk native vlan 99', accept: ['sw trunk native vlan 99'],
    note: 'Both ends must match. A mismatch silently bridges the two native VLANs.' },
  { id: 'cmd-portfast', domain: 'NA', kind: 'command', prompt: 'On an access port, skip the spanning tree listening and learning delay.',
    answer: 'spanning-tree portfast', accept: ['span portfast', 'spanning-tree port'],
    note: 'Edge ports only. Pair it with BPDU guard.' },
  { id: 'cmd-bpduguard', domain: 'SECF', kind: 'command', prompt: 'On an access port, err-disable it if it ever receives a BPDU.',
    answer: 'spanning-tree bpduguard enable', accept: ['span bpduguard enable', 'spanning-tree bpdu enable'],
    note: 'Keeps someone from plugging a switch into a user jack and disturbing your topology.' },
  { id: 'cmd-psec-max', domain: 'SECF', kind: 'command', prompt: 'On a secured port, allow at most two MAC addresses.',
    answer: 'switchport port-security maximum 2', accept: ['sw port-security maximum 2', 'sw port-sec max 2', 'switchport port-security max 2'],
    note: 'Port security itself has to be enabled with switchport port-security or this does nothing.' },
  { id: 'cmd-channel', domain: 'NA', kind: 'command', prompt: 'Add an interface to EtherChannel group 1, actively negotiating with LACP.',
    answer: 'channel-group 1 mode active', accept: ['channel-group 1 mo active'],
    note: 'Active pairs with active or passive. Passive with passive never forms, because nobody starts.' },
  { id: 'cmd-helper', domain: 'IPS', kind: 'command', prompt: 'On the interface facing the clients, relay DHCP to a server at 10.1.1.5.',
    answer: 'ip helper-address 10.1.1.5', accept: ['ip helper 10.1.1.5'],
    note: 'Goes on the client-facing interface, not the one facing the server.' },

  // ---------- routing and services ----------
  { id: 'cmd-default', domain: 'IPC', kind: 'command', prompt: 'Install a default route with a next hop of 203.0.113.1.',
    answer: 'ip route 0.0.0.0 0.0.0.0 203.0.113.1', accept: [],
    note: 'Destination, then mask, then next hop. All zeros matches anything not matched more specifically.' },
  { id: 'cmd-ospf', domain: 'IPC', kind: 'command', prompt: 'Start OSPF process 1.',
    answer: 'router ospf 1', accept: [],
    note: 'The process ID is local to the router and does not have to match its neighbors.' },
  { id: 'cmd-ospf-net', domain: 'IPC', kind: 'command', prompt: 'Under OSPF, enable it on 10.0.0.0/24 in area 0.',
    answer: 'network 10.0.0.0 0.0.0.255 area 0', accept: [],
    note: 'OSPF takes a wildcard mask, the inverse of the subnet mask.' },
  { id: 'cmd-acl-apply', domain: 'SECF', kind: 'command', prompt: 'On an interface, apply ACL 101 to incoming traffic.',
    answer: 'ip access-group 101 in', accept: [],
    note: 'Access-group on an interface, access-class on vty lines. The two are easy to confuse.' },
  { id: 'cmd-ssh-only', domain: 'SECF', kind: 'command', prompt: 'On the vty lines, permit SSH and refuse Telnet.',
    answer: 'transport input ssh', accept: [],
    note: 'Needs a hostname, a domain name, and generated RSA keys before SSH will actually work.' },
  { id: 'cmd-rsa', domain: 'SECF', kind: 'command', prompt: 'Generate the RSA key pair SSH needs.',
    answer: 'crypto key generate rsa', accept: ['cry key gen rsa'],
    note: 'Fails until hostname and ip domain-name are both set, because the key is named after them.' },
  { id: 'cmd-nat-in', domain: 'IPS', kind: 'command', prompt: 'Mark an interface as the inside of the NAT boundary.',
    answer: 'ip nat inside', accept: [],
    note: 'Every NAT configuration needs both an inside and an outside interface marked.' },

  // ---------- numbers worth knowing cold ----------
  { id: 'num-ad-static', domain: 'IPC', kind: 'fact', prompt: 'Administrative distance of a static route.',
    answer: '1', accept: [], note: 'Only a directly connected network, at 0, is trusted more.' },
  { id: 'num-ad-ospf', domain: 'IPC', kind: 'fact', prompt: 'Administrative distance of OSPF.',
    answer: '110', accept: [], note: 'Higher than static at 1 and EIGRP at 90, lower than RIP at 120.' },
  { id: 'num-ad-eigrp', domain: 'IPC', kind: 'fact', prompt: 'Administrative distance of internal EIGRP.',
    answer: '90', accept: [], note: 'External EIGRP routes are 170.' },
  { id: 'num-hello', domain: 'IPC', kind: 'fact', prompt: 'OSPF hello interval on a broadcast network, in seconds.',
    answer: '10', accept: ['10 seconds', '10s'], note: 'The dead interval defaults to four times the hello, so 40. Both must match between neighbors.' },
  { id: 'num-dead', domain: 'IPC', kind: 'fact', prompt: 'OSPF dead interval on a broadcast network, in seconds.',
    answer: '40', accept: ['40 seconds', '40s'], note: 'Four hellos missed and the neighbor is declared down.' },
  { id: 'num-ospf-mcast', domain: 'IPC', kind: 'fact', prompt: 'Multicast address OSPF uses to reach all OSPF routers.',
    answer: '224.0.0.5', accept: [], note: '224.0.0.6 reaches only the DR and BDR.' },
  { id: 'num-stp-pri', domain: 'NA', kind: 'fact', prompt: 'Default spanning tree bridge priority.',
    answer: '32768', accept: [], note: 'Priority moves in steps of 4096, so the next lower value is 28672.' },
  { id: 'num-vlan-max', domain: 'NA', kind: 'fact', prompt: 'Highest usable VLAN ID.',
    answer: '4094', accept: [], note: 'The 12-bit field allows 4096 values, and 0 and 4095 are reserved.' },
  { id: 'num-dscp-ef', domain: 'IPS', kind: 'fact', prompt: 'DSCP decimal value for EF, used for voice.',
    answer: '46', accept: [], note: 'Voice signalling is usually marked CS3, decimal 24.' },
  { id: 'num-capwap', domain: 'NA', kind: 'fact', prompt: 'UDP port for CAPWAP control traffic between an AP and a WLC.',
    answer: '5246', accept: ['udp 5246'], note: 'Client data uses 5247. An AP that cannot reach 5246 on its controller never joins, so it serves nothing at all.' },
  { id: 'num-link-local', domain: 'NF', kind: 'fact', prompt: 'IPv6 prefix for link-local addresses.',
    answer: 'fe80::/10', accept: ['fe80::'], note: 'Every IPv6 interface builds one automatically, and routers never forward it.' },

  // ---------- well-known ports ----------
  { id: 'port-ssh', domain: 'IPS', kind: 'fact', prompt: 'Port number for SSH.', answer: '22', accept: ['tcp 22'], note: 'Telnet is 23 and sends everything in clear text.' },
  { id: 'port-dns', domain: 'IPS', kind: 'fact', prompt: 'Port number for DNS.', answer: '53', accept: ['udp 53', 'tcp 53'], note: 'UDP for queries, TCP for large responses and zone transfers.' },
  { id: 'port-https', domain: 'IPS', kind: 'fact', prompt: 'Port number for HTTPS.', answer: '443', accept: ['tcp 443'], note: 'Plain HTTP is 80. An ACL permitting only 443 breaks the redirect many sites use to move a visitor from 80 to 443.' },
  { id: 'port-snmp', domain: 'IPS', kind: 'fact', prompt: 'Port number SNMP agents listen on.', answer: '161', accept: ['udp 161'], note: 'Traps and informs are sent to the manager on 162.' },
  { id: 'port-syslog', domain: 'IPS', kind: 'fact', prompt: 'Port number for syslog.', answer: '514', accept: ['udp 514'], note: 'Severity 0 is emergency and 7 is debugging.' },
  { id: 'port-ntp', domain: 'IPS', kind: 'fact', prompt: 'Port number for NTP.', answer: '123', accept: ['udp 123'], note: 'Lower stratum numbers sit closer to the reference clock.' },
  { id: 'port-dhcp', domain: 'IPS', kind: 'fact', prompt: 'Port number a DHCP server listens on.', answer: '67', accept: ['udp 67'], note: 'Clients listen on 68. The request is a broadcast, which is why a router needs ip helper-address to pass it to another subnet.' },
  { id: 'port-tftp', domain: 'IPS', kind: 'fact', prompt: 'Port number for TFTP.', answer: '69', accept: ['udp 69'], note: 'No authentication at all, which is why it is used for images on trusted networks only.' },

  // ---------- name resolution ----------
  { id: 'cmd-nslookup', domain: 'IPS', kind: 'command', prompt: 'On Windows, query DNS for portal.example.com.',
    answer: 'nslookup portal.example.com', accept: [],
    note: 'Prints the answer and the server that gave it. A timeout means the resolver is unreachable; a wrong answer means the record is wrong.' },
  { id: 'cmd-ipconfig-all', domain: 'IPS', kind: 'command', prompt: 'On Windows, show the DNS servers a host is using.',
    answer: 'ipconfig /all', accept: ['ipconfig/all'],
    note: 'Plain ipconfig omits the DNS servers, which is why the resolver setting gets missed.' },
  { id: 'cmd-name-server', domain: 'IPS', kind: 'command', prompt: 'On a Cisco device, use 10.1.1.53 as the DNS server.',
    answer: 'ip name-server 10.1.1.53', accept: [],
    note: 'Lookups also need ip domain-lookup enabled, which is on by default and often turned off to stop typos hanging the console.' },
  { id: 'cmd-domain-lookup', domain: 'IPS', kind: 'command', prompt: 'On a Cisco device, turn DNS lookups back on.',
    answer: 'ip domain-lookup', accept: ['ip domain lookup'],
    note: 'With it on, a mistyped command is treated as a hostname and the console hangs trying to resolve it, which is why many labs disable it.' },
];
