// The CCNA skill map: seven trees, each split into branches.
//
// Tree 0 is the IOS trunk every hands-on tier depends on; trees 1 to 6 are the
// six domains of the CCNA 200-301 v1.1 blueprint, with their exam weights.
//
// A branch is the unit that carries lights. Each has up to three tiers:
//   know  recall and explain it         (questions from the bank)
//   do    build it from the command line (console labs, still to come)
//   fix   find and repair it            (tickets)
// Concept-only branches stop at know. `topics` is what the branch covers, shown
// in its panel; `match` tags bank questions to the branch; `recipes` are the
// ticket faults that light its fix tier; `needs` are prerequisite branches,
// which mark a branch harder but never lock it.
//
// Pure data. Another certification is another file shaped like this one.

export const TIERS = ['know', 'do', 'fix'];

export const CCNA_MAP = {
  id: 'ccna',
  title: 'CCNA 200-301',
  trees: [
    {
      id: 't0', num: 0, name: 'IOS Foundations', short: 'IOS', domain: null, weight: null,
      blurb: 'The command line every hands-on tier runs on.',
      branches: [
        { id: 't0-nav', name: 'Navigate', tiers: ['know', 'do'], needs: [],
          topics: ['User, privileged, global and interface modes', '? and Tab', 'do from config mode', 'Abbreviations'],
          match: /privileged exec|global config|configuration mode|user exec|\bdo show\b|abbreviat/i },
        { id: 't0-inspect', name: 'Inspect', tiers: ['know', 'do', 'fix'], needs: ['t0-nav'],
          topics: ['show running-config', 'show ip interface brief', 'show interfaces', 'show version', 'Filtering output'],
          match: /show (ip interface brief|interfaces?\b|version|running)|\| include|interface status|up\/down|line protocol/i },
        { id: 't0-base', name: 'Base config', tiers: ['know', 'do', 'fix'], needs: ['t0-nav'], recipes: ['P2'],
          topics: ['Hostname', 'enable secret', 'Banners', 'Interface IP and description', 'no shutdown'],
          match: /enable secret|enable password|hostname|banner|no shutdown|administratively down/i },
        { id: 't0-save', name: 'Save and restore', tiers: ['know', 'do'], needs: ['t0-base'],
          topics: ['Running vs startup config', 'copy running-config startup-config', 'Reload'],
          match: /startup-config|copy run|write memory|nvram|reload/i },
        { id: 't0-remote', name: 'Remote access', tiers: ['know', 'do', 'fix'], needs: ['t0-base'],
          topics: ['Local users', 'VTY lines', 'SSH', 'transport input ssh'],
          match: /\bssh\b|telnet|\bvty\b|transport input|crypto key/i },
      ],
    },
    {
      id: 't1', num: 1, name: 'Network Fundamentals', short: 'Fundamentals', domain: 'NF', weight: 20,
      blurb: 'What the parts are and how addresses work.',
      branches: [
        { id: 't1-devices', name: 'Devices and roles', tiers: ['know'], needs: [],
          topics: ['Routers', 'L2 and L3 switches', 'Firewalls and IPS', 'Access points and controllers', 'Endpoints and servers', 'PoE'],
          match: /firewall|\bips\b|next-generation|\bpoe\b|power over ethernet|layer 3 switch|endpoint|controller role/i },
        { id: 't1-arch', name: 'Architectures', tiers: ['know'], needs: ['t1-devices'],
          topics: ['Two-tier and three-tier', 'Spine-leaf', 'WAN', 'Small office', 'On-premises vs cloud'],
          match: /spine|leaf|three-tier|two-tier|collapsed core|\bwan\b|soho|cloud|on-prem|topology architecture/i },
        { id: 't1-physical', name: 'Physical layer', tiers: ['know', 'do', 'fix'], needs: [], recipes: ['P1'],
          topics: ['Copper and fiber', 'Interface errors', 'Duplex and speed mismatch', 'Collisions'],
          match: /fiber|fibre|multimode|single-mode|singlemode|copper|utp|cable|duplex|collision|crc|runts|giants|speed mismatch|sfp/i },
        { id: 't1-transport', name: 'TCP, UDP, ports', tiers: ['know'], needs: [],
          topics: ['TCP vs UDP', 'Well-known ports', 'Three-way handshake'],
          match: /\btcp\b|\budp\b|port number|well-known port|handshake|syn\b/i },
        { id: 't1-ipv4', name: 'IPv4 and subnetting', tiers: ['know', 'do', 'fix'], needs: [], recipes: ['I1'],
          topics: ['Addressing', 'Subnetting', 'Private ranges (RFC 1918)'],
          match: /subnet|\/2[4-9]|\/3[0-2]|mask|rfc 1918|private (ip|range|address)|broadcast address|usable host|ipv4 address/i },
        { id: 't1-ipv6', name: 'IPv6 addressing', tiers: ['know', 'do', 'fix'], needs: ['t1-ipv4'],
          topics: ['Address types', 'Prefixes', 'EUI-64', 'SLAAC'],
          match: /ipv6|fe80|eui-64|slaac|link-local|global unicast|unique local|anycast/i },
        { id: 't1-client', name: 'Client addressing', tiers: ['know', 'do', 'fix'], needs: ['t1-ipv4'], recipes: ['I2'],
          topics: ['ipconfig, ifconfig, ip addr', 'Default gateway on the host', 'Verifying IP settings'],
          match: /ipconfig|ifconfig|ip addr|default gateway|apipa|169\.254|host.*gateway/i },
        { id: 't1-wireless', name: 'Wireless basics', tiers: ['know'], needs: [],
          topics: ['Channels and overlap', 'SSID', 'RF', 'Encryption basics'],
          match: /channel|ssid|2\.4 ?ghz|5 ?ghz|\brf\b|wireless|wi-?fi|802\.11/i },
        { id: 't1-virtual', name: 'Virtualization', tiers: ['know'], needs: ['t1-devices'],
          topics: ['Virtual machines', 'Containers', 'VRFs'],
          match: /virtual machine|hypervisor|container|\bvrf\b|virtualiz/i },
        { id: 't1-switching', name: 'Switching', tiers: ['know', 'do'], needs: [],
          topics: ['MAC learning and aging', 'Frame switching', 'Flooding'],
          match: /mac address table|mac table|cam table|flood|unknown unicast|frame|broadcast domain|collision domain/i },
      ],
    },
    {
      id: 't2', num: 2, name: 'Network Access', short: 'Access', domain: 'NA', weight: 20,
      blurb: 'Getting hosts onto the right part of the switch fabric.',
      branches: [
        { id: 't2-vlans', name: 'VLANs', tiers: ['know', 'do', 'fix'], needs: ['t1-switching'], recipes: ['V1'],
          topics: ['Access ports', 'Data and voice VLANs', 'Default VLAN'],
          match: /\bvlan\b|access port|voice vlan|switchport access/i },
        { id: 't2-trunks', name: 'Trunks', tiers: ['know', 'do', 'fix'], needs: ['t2-vlans'], recipes: ['V2'],
          topics: ['802.1Q', 'Native VLAN', 'Allowed VLAN list', 'DTP'],
          match: /trunk|802\.1q|native vlan|allowed vlan|dtp|dynamic (auto|desirable)/i },
        { id: 't2-discovery', name: 'CDP and LLDP', tiers: ['know', 'do'], needs: ['t0-inspect'],
          topics: ['CDP', 'LLDP', 'Finding neighbors'],
          match: /\bcdp\b|\blldp\b|neighbor discovery|directly connected (cisco )?device/i },
        { id: 't2-etherchannel', name: 'EtherChannel', tiers: ['know', 'do', 'fix'], needs: ['t2-trunks'],
          topics: ['LACP', 'Bundling', 'Mismatches'],
          match: /etherchannel|lacp|pagp|port-channel|bundl/i },
        { id: 't2-stp', name: 'Spanning tree', tiers: ['know', 'do', 'fix'], needs: ['t2-trunks'],
          topics: ['Root bridge', 'Port roles and states', 'Rapid PVST+', 'PortFast and BPDU Guard'],
          match: /spanning|stp|rstp|root bridge|root port|designated port|portfast|bpdu|bridge id|blocking|alternate port/i },
        { id: 't2-wlan-arch', name: 'AP and WLC roles', tiers: ['know'], needs: ['t1-wireless'],
          topics: ['AP modes', 'CAPWAP', 'Wireless LAN controllers', 'Management access'],
          match: /capwap|\bwlc\b|lightweight|autonomous|flexconnect|ap mode|controller/i },
        { id: 't2-wlc', name: 'WLC setup', tiers: ['know'], needs: ['t2-wlan-arch'],
          topics: ['Creating a WLAN in the GUI', 'Interfaces and ports on a WLC'],
          match: /create (a )?wlan|wlan .*gui|lag on the wlc|dynamic interface/i },
      ],
    },
    {
      id: 't3', num: 3, name: 'IP Connectivity', short: 'Routing', domain: 'IPC', weight: 25,
      blurb: 'How packets find their way. The biggest slice of the exam.',
      branches: [
        { id: 't3-table', name: 'Routing table', tiers: ['know', 'do'], needs: ['t1-ipv4'],
          topics: ['Route codes', 'Prefix and next hop', 'Metric', 'Administrative distance'],
          match: /routing table|show ip route|route code|next hop|next-hop|gateway of last resort/i },
        { id: 't3-forwarding', name: 'Forwarding decision', tiers: ['know', 'fix'], needs: ['t3-table'],
          topics: ['Longest prefix match', 'Administrative distance', 'Metric'],
          match: /longest|prefix match|administrative distance|\bad\b|metric|most specific/i },
        { id: 't3-static', name: 'Static routing', tiers: ['know', 'do', 'fix'], needs: ['t3-table'],
          topics: ['Default route', 'Network and host routes', 'Floating static', 'IPv6 static routes'],
          match: /static route|ip route|default route|floating|ipv6 route|0\.0\.0\.0\/0|::\/0/i },
        { id: 't3-ospf', name: 'OSPF', tiers: ['know', 'do', 'fix'], needs: ['t3-static'],
          topics: ['Neighbor adjacency', 'Point-to-point', 'Broadcast with DR and BDR', 'Router ID'],
          match: /ospf|\bdr\b|\bbdr\b|router id|router-id|adjacenc|hello|dead interval|area 0|lsa/i },
        { id: 't3-fhrp', name: 'First-hop redundancy', tiers: ['know'], needs: ['t3-table'],
          topics: ['HSRP', 'Virtual gateway', 'Active and standby'],
          match: /hsrp|vrrp|glbp|first.hop|virtual (ip|gateway|mac)|standby/i },
      ],
    },
    {
      id: 't4', num: 4, name: 'IP Services', short: 'Services', domain: 'IPS', weight: 10,
      blurb: 'The services that keep a network usable.',
      branches: [
        { id: 't4-nat', name: 'NAT and PAT', tiers: ['know', 'do', 'fix'], needs: ['t1-ipv4', 't5-acl'],
          topics: ['Static NAT', 'Pools', 'PAT (overload)', 'Inside and outside'],
          match: /\bnat\b|\bpat\b|overload|inside local|inside global|outside (local|global)/i },
        { id: 't4-ntp-log', name: 'Time and logging', tiers: ['know', 'do'], needs: ['t0-base'],
          topics: ['NTP client and server', 'Syslog levels'],
          match: /\bntp\b|stratum|syslog|severity|logging|clock/i },
        { id: 't4-dhcp-dns', name: 'DHCP and DNS', tiers: ['know', 'do', 'fix'], needs: ['t1-client'], recipes: ['D1', 'D2'],
          topics: ['DNS lookups and records', 'DHCP leases', 'DHCP relay (ip helper-address)'],
          match: /dhcp|\bdns\b|helper-address|\bdora\b|lease|resolver|a record|nslookup/i },
        { id: 't4-snmp', name: 'SNMP', tiers: ['know'], needs: [],
          topics: ['Managers and agents', 'Traps and polling', 'Versions'],
          match: /snmp|\bmib\b|trap/i },
        { id: 't4-qos', name: 'QoS', tiers: ['know'], needs: [],
          topics: ['Classification and marking', 'Queuing', 'Policing and shaping'],
          match: /qos|dscp|\bcos\b|queu|polic|shap|marking|jitter|latency/i },
        { id: 't4-files', name: 'TFTP and FTP', tiers: ['know'], needs: [],
          topics: ['TFTP', 'FTP', 'Moving IOS images and configs'],
          match: /tftp|\bftp\b|file transfer/i },
      ],
    },
    {
      id: 't5', num: 5, name: 'Security Fundamentals', short: 'Security', domain: 'SECF', weight: 15,
      blurb: 'Keeping the wrong traffic and the wrong people out.',
      branches: [
        { id: 't5-concepts', name: 'Security concepts', tiers: ['know'], needs: [],
          topics: ['Threats, vulnerabilities, exploits', 'Mitigation', 'Security programs and training'],
          match: /threat|vulnerab|exploit|mitigat|phishing|social engineering|malware|ddos|spoof|security program/i },
        { id: 't5-access', name: 'Device access', tiers: ['know', 'do'], needs: ['t0-base'],
          topics: ['Local passwords', 'Password policy', 'MFA', 'Certificates and biometrics'],
          match: /password|\bmfa\b|multifactor|multi-factor|certificate|biometric/i },
        { id: 't5-vpn', name: 'VPNs', tiers: ['know'], needs: [],
          topics: ['Site-to-site IPsec', 'Remote-access VPN'],
          match: /\bvpn\b|ipsec|tunnel|remote access vpn|site-to-site/i },
        { id: 't5-acl', name: 'ACLs', tiers: ['know', 'do', 'fix'], needs: ['t1-ipv4', 't1-transport'],
          topics: ['Standard ACLs', 'Extended ACLs', 'Wildcard masks', 'Placement and direction'],
          match: /\bacl\b|access-list|access list|wildcard|implicit deny|permit|deny/i },
        { id: 't5-l2sec', name: 'Layer 2 security', tiers: ['know', 'do', 'fix'], needs: ['t2-vlans'],
          topics: ['Port security', 'DHCP snooping', 'Dynamic ARP inspection'],
          match: /port security|port-security|sticky|violation|dhcp snooping|arp inspection|\bdai\b|err-disabled/i },
        { id: 't5-aaa', name: 'AAA', tiers: ['know'], needs: ['t5-access'],
          topics: ['Authentication, authorization, accounting', 'RADIUS', 'TACACS+'],
          match: /\baaa\b|radius|tacacs|authoriz|accounting/i },
        { id: 't5-wsec', name: 'Wireless security', tiers: ['know'], needs: ['t2-wlan-arch'],
          topics: ['WPA, WPA2, WPA3', 'PSK vs Enterprise', 'A WPA2-PSK WLAN in the GUI'],
          match: /wpa|\bpsk\b|802\.1x|\bsae\b|\btkip\b|\baes\b/i },
      ],
    },
    {
      id: 't6', num: 6, name: 'Automation', short: 'Automation', domain: 'AUTO', weight: 10,
      blurb: 'Networks run by software instead of by hand.',
      branches: [
        { id: 't6-sdn', name: 'Controller-based networking', tiers: ['know'], needs: [],
          topics: ['Traditional vs controller-based', 'SDN', 'Overlay and underlay', 'Northbound and southbound APIs'],
          match: /sdn|controller|overlay|underlay|fabric|northbound|southbound|control plane|data plane|dna center|catalyst center/i },
        { id: 't6-ai', name: 'AI and ML in operations', tiers: ['know'], needs: [],
          topics: ['Predictive AI', 'Generative AI', 'Machine learning for operations'],
          match: /\bai\b|machine learning|\bml\b|predictive|generative|artificial intelligence/i },
        { id: 't6-rest', name: 'REST APIs', tiers: ['know'], needs: ['t6-sdn'],
          topics: ['CRUD', 'HTTP verbs', 'Status codes', 'Data encoding'],
          match: /\brest\b|\bapi\b|http (get|post|put|delete|verb)|\bcrud\b|status code|\b(get|post|put|patch|delete)\b request/i },
        { id: 't6-config', name: 'Configuration management', tiers: ['know'], needs: [],
          topics: ['Ansible', 'Terraform', 'Puppet and Chef'],
          match: /ansible|terraform|puppet|chef|playbook|agentless|infrastructure as code/i },
        { id: 't6-json', name: 'JSON', tiers: ['know', 'do'], needs: [],
          topics: ['Objects and arrays', 'Key and value pairs', 'Reading JSON output'],
          match: /json|key.value|curly brace|array/i },
      ],
    },
  ],
};

export const ALL_BRANCHES = CCNA_MAP.trees.flatMap(t => t.branches.map(b => ({ ...b, treeId: t.id })));
export const branchById = (id) => ALL_BRANCHES.find(b => b.id === id) ?? null;
export const treeById = (id) => CCNA_MAP.trees.find(t => t.id === id) ?? null;
export const treeOfBranch = (id) => treeById(branchById(id)?.treeId);
